export const questions_ch7 = [
  // Bài 1: Định lí Thalès trong tam giác (10 câu)
  { id: "ch7_1_1", category: "Chương 7 - Bài 1", timeLimit: 30, question: "Nội dung gốc của định lí Thalès nói về điều gì?", options: [{ id: "A", text: "Trọng tâm tam giác", isCorrect: false }, { id: "B", text: "Hai đường thẳng song song chắn trên hai đường thẳng cắt nhau tạo ra đoạn tỉ lệ", isCorrect: true }, { id: "C", text: "Khai căn phương trình", isCorrect: false }, { id: "D", text: "Trực tâm tam giác", isCorrect: false }] },
  { id: "ch7_1_2", category: "Chương 7 - Bài 1", timeLimit: 30, question: "Cho $\\Delta ABC$ có $MN \\parallel BC$ ($M \\in AB, N \\in AC$). Hệ thức nào bị sai?", options: [{ id: "A", text: "$\\frac{AM}{AB} = \\frac{AN}{AC}$", isCorrect: false }, { id: "B", text: "$\\frac{AM}{MB} = \\frac{AN}{NC}$", isCorrect: false }, { id: "C", text: "$\\frac{AB}{AM} = \\frac{AC}{NC}$", isCorrect: true }, { id: "D", text: "$\\frac{MB}{AB} = \\frac{NC}{AC}$", isCorrect: false }] },
  { id: "ch7_1_3", category: "Chương 7 - Bài 1", timeLimit: 30, question: "Định lí đảo của định lí Thalès dùng để làm gì?", options: [{ id: "A", text: "Chứng minh tam giác cân", isCorrect: false }, { id: "B", text: "Tính đường trung bình", isCorrect: false }, { id: "C", text: "Chứng minh đường phân giác", isCorrect: false }, { id: "D", text: "Chứng minh hai đường thẳng song song", isCorrect: true }] },
  { id: "ch7_1_4", category: "Chương 7 - Bài 1", timeLimit: 30, question: "Hệ quả của định lí Thalès cho phép ta suy ra tỉ số của:", options: [{ id: "A", text: "Diện tích hai tam giác", isCorrect: false }, { id: "B", text: "Các cạnh tương ứng của hai tam giác tạo thành", isCorrect: true }, { id: "C", text: "Các góc trong tam giác", isCorrect: false }, { id: "D", text: "Cạnh và góc xen giữa", isCorrect: false }] },
  { id: "ch7_1_5", category: "Chương 7 - Bài 1", timeLimit: 30, question: "Cho $MN$ song song với $BC$ của $\\Delta ABC$. Nếu $\\frac{AM}{AB} = \\frac{1}{3}$, tỉ số $\\frac{MN}{BC}$ là:", options: [{ id: "A", text: "$\\frac{1}{2}$", isCorrect: false }, { id: "B", text: "$\\frac{1}{4}$", isCorrect: false }, { id: "C", text: "$\\frac{1}{3}$", isCorrect: true }, { id: "D", text: "$\\frac{2}{3}$", isCorrect: false }] },
  { id: "ch7_1_6", category: "Chương 7 - Bài 1", timeLimit: 30, question: "Trong $\\Delta MNP$, có đường thẳng $d \\parallel NP$ cắt $MN$ tại $D$ và $MP$ tại $E$. Biết $MD = 4$cm, $DN = 2$cm, $ME = 6$cm. Tính $EP$.", options: [{ id: "A", text: "$4$ cm", isCorrect: false }, { id: "B", text: "$3$ cm", isCorrect: true }, { id: "C", text: "$2$ cm", isCorrect: false }, { id: "D", text: "$5$ cm", isCorrect: false }] },
  { id: "ch7_1_7", category: "Chương 7 - Bài 1", timeLimit: 30, question: "Nếu $\\frac{AD}{DB} = \\frac{AE}{EC}$ trong $\\Delta ABC$, thì:", options: [{ id: "A", text: "$DE \\perp BC$", isCorrect: false }, { id: "B", text: "$DE = \\frac{1}{2} BC$", isCorrect: false }, { id: "C", text: "$DE$ là đường trung tuyến", isCorrect: false }, { id: "D", text: "$DE \\parallel BC$", isCorrect: true }] },
  { id: "ch7_1_8", category: "Chương 7 - Bài 1", timeLimit: 30, question: "Với hình thang $ABCD$ ($AB \\parallel CD$), một đường $MN \\parallel AB$ ($M \\in AD, N \\in BC$). Khi đó:", options: [{ id: "A", text: "$AM = MD$", isCorrect: false }, { id: "B", text: "$\\frac{AM}{MD} = \\frac{BN}{NC}$", isCorrect: true }, { id: "C", text: "$\\frac{AM}{MD} = \\frac{NC}{BN}$", isCorrect: false }, { id: "D", text: "$MN$ phải là nửa tổng 2 đáy", isCorrect: false }] },
  { id: "ch7_1_9", category: "Chương 7 - Bài 1", timeLimit: 30, question: "Hai đường kính giao nhau cũng tạo ra các cặp đoạn tỉ lệ thuận nhờ định lí:", options: [{ id: "A", text: "Pythagore", isCorrect: false }, { id: "B", text: "Euler", isCorrect: false }, { id: "C", text: "Thalès", isCorrect: true }, { id: "D", text: "Ceva", isCorrect: false }] },
  { id: "ch7_1_10", category: "Chương 7 - Bài 1", timeLimit: 30, question: "Nếu một đường thẳng cắt hai cạnh tam giác và kéo dài thì đoạn thứ 3 sinh ra từ giao điểm kéo dài phải:", options: [{ id: "A", text: "Tạo các cặp đoạn cân đối theo hệ quả Thalès", isCorrect: true }, { id: "B", text: "Luôn bé hơn cạnh tam giác", isCorrect: false }, { id: "C", text: "Tạo góc vuông", isCorrect: false }, { id: "D", text: "Song song với trung tuyến", isCorrect: false }] },

  // Bài 2: Đường trung bình của tam giác (10 câu)
  { id: "ch7_2_1", category: "Chương 7 - Bài 2", timeLimit: 30, question: "Đường trung bình của tam giác là đoạn thẳng nối:", options: [{ id: "A", text: "Đỉnh với trọng tâm", isCorrect: false }, { id: "B", text: "Trung điểm của hai cạnh tam giác", isCorrect: true }, { id: "C", text: "Đỉnh với trực tâm", isCorrect: false }, { id: "D", text: "Trực tâm và giao ba đường phân giác", isCorrect: false }] },
  { id: "ch7_2_2", category: "Chương 7 - Bài 2", timeLimit: 30, question: "Tính chất 1 của đường trung bình của tam giác:", options: [{ id: "A", text: "Song song với cạnh thứ ba", isCorrect: true }, { id: "B", text: "Vuông góc với cạnh thứ ba", isCorrect: false }, { id: "C", text: "Cắt cạnh thứ ba $\\frac{1}{3}$ đoạn", isCorrect: false }, { id: "D", text: "Bằng với cạnh thứ ba", isCorrect: false }] },
  { id: "ch7_2_3", category: "Chương 7 - Bài 2", timeLimit: 30, question: "Tính chất 2 của đường trung bình của tam giác:", options: [{ id: "A", text: "Bằng chu vi tam giác nhỏ", isCorrect: false }, { id: "B", text: "Bằng $\\frac{1}{3}$ cạnh thứ ba", isCorrect: false }, { id: "C", text: "Bằng nửa cạnh thứ ba", isCorrect: true }, { id: "D", text: "Bằng $1.5$ lần cạnh thứ ba", isCorrect: false }] },
  { id: "ch7_2_4", category: "Chương 7 - Bài 2", timeLimit: 30, question: "Đường thẳng đi qua trung điểm một cạnh và song song với cạnh thứ hai thì:", options: [{ id: "A", text: "Vuông góc cạnh thứ ba", isCorrect: false }, { id: "B", text: "Cắt cạnh thứ ba tại trung điểm của nó", isCorrect: true }, { id: "C", text: "Song song cạnh thứ ba", isCorrect: false }, { id: "D", text: "Là đường cao", isCorrect: false }] },
  { id: "ch7_2_5", category: "Chương 7 - Bài 2", timeLimit: 30, question: "Trong một tam giác có tối đa bao nhiêu đường trung bình?", options: [{ id: "A", text: "1", isCorrect: false }, { id: "B", text: "2", isCorrect: false }, { id: "C", text: "4", isCorrect: false }, { id: "D", text: "3", isCorrect: true }] },
  { id: "ch7_2_6", category: "Chương 7 - Bài 2", timeLimit: 30, question: "Chu vi của tam giác tạo bởi 3 đường trung bình bằng:", options: [{ id: "A", text: "Bằng chu vi tam giác gốc", isCorrect: false }, { id: "B", text: "Gấp đôi chu vi tam giác gốc", isCorrect: false }, { id: "C", text: "Bằng nửa chu vi tam giác gốc", isCorrect: true }, { id: "D", text: "Bằng $\\frac{1}{3}$ chu vi gốc", isCorrect: false }] },
  { id: "ch7_2_7", category: "Chương 7 - Bài 2", timeLimit: 30, question: "Cho $\\Delta ABC$, $M, N$ là trung điểm $AB, AC$. Nếu $BC = 12$cm thì $MN$ bằng:", options: [{ id: "A", text: "$4$cm", isCorrect: false }, { id: "B", text: "$6$cm", isCorrect: true }, { id: "C", text: "$8$cm", isCorrect: false }, { id: "D", text: "$24$cm", isCorrect: false }] },
  { id: "ch7_2_8", category: "Chương 7 - Bài 2", timeLimit: 30, question: "Tam giác có ba đường trung bình bằng nhau thuộc loại tam giác nào?", options: [{ id: "A", text: "Tam giác cân", isCorrect: false }, { id: "B", text: "Tam giác vuông", isCorrect: false }, { id: "C", text: "Tam giác đều", isCorrect: true }, { id: "D", text: "Tam giác nhọn", isCorrect: false }] },
  { id: "ch7_2_9", category: "Chương 7 - Bài 2", timeLimit: 30, question: "Tứ giác được tạo thành khi nối 4 trung điểm của tứ giác không bằng nhau là hình gì?", options: [{ id: "A", text: "Hình bình hành", isCorrect: true }, { id: "B", text: "Hình thang", isCorrect: false }, { id: "C", text: "Hình chữ nhật", isCorrect: false }, { id: "D", text: "Hình vuông", isCorrect: false }] },
  { id: "ch7_2_10", category: "Chương 7 - Bài 2", timeLimit: 30, question: "Nếu đoạn thẳng $MN$ là đường trung bình của tam giác và cũng vuông góc cạnh còn lại thì tam giác đó:", options: [{ id: "A", text: "Vuông", isCorrect: true }, { id: "B", text: "Đều", isCorrect: false }, { id: "C", text: "Tù", isCorrect: false }, { id: "D", text: "Vuông cân", isCorrect: false }] },

  // Bài 3: Tính chất đường phân giác của tam giác (10 câu)
  { id: "ch7_3_1", category: "Chương 7 - Bài 3", timeLimit: 30, question: "Trong tam giác, đường phân giác của một góc chia cạnh đối diện thành hai đoạn tỉ lệ với:", options: [{ id: "A", text: "Hai chân đường cao", isCorrect: false }, { id: "B", text: "Hai cạnh kề với hai đoạn ấy", isCorrect: true }, { id: "C", text: "Chu vi tam giác", isCorrect: false }, { id: "D", text: "Đường trung tuyến của đoạn ấy", isCorrect: false }] },
  { id: "ch7_3_2", category: "Chương 7 - Bài 3", timeLimit: 30, question: "Cho $\\Delta ABC$, $AD$ là phân giác góc $A$. Hệ thức nào đúng?", options: [{ id: "A", text: "$\\frac{DB}{DC} = \\frac{AB}{AC}$", isCorrect: true }, { id: "B", text: "$\\frac{DB}{DC} = \\frac{AC}{AB}$", isCorrect: false }, { id: "C", text: "$\\frac{DB}{AB} = \\frac{AC}{DC}$", isCorrect: false }, { id: "D", text: "$\\frac{AD}{DB} = \\frac{AB}{AC}$", isCorrect: false }] },
  { id: "ch7_3_3", category: "Chương 7 - Bài 3", timeLimit: 30, question: "Tính chất phân giác trong tam giác áp dụng được cho:", options: [{ id: "A", text: "Cả góc trong và phân giác góc ngoài", isCorrect: true }, { id: "B", text: "Chỉ góc trong góc nhọn", isCorrect: false }, { id: "C", text: "Chỉ phân giác góc ngoài", isCorrect: false }, { id: "D", text: "Chỉ cho góc vuông", isCorrect: false }] },
  { id: "ch7_3_4", category: "Chương 7 - Bài 3", timeLimit: 30, question: "Hai đường phân giác (trong và ngoài) tại một đỉnh của tam giác có quan hệ gì?", options: [{ id: "A", text: "Trùng nhau", isCorrect: false }, { id: "B", text: "Tạo thành góc $180^\\circ$", isCorrect: false }, { id: "C", text: "Nằm khác phía", isCorrect: false }, { id: "D", text: "Vuông góc với nhau", isCorrect: true }] },
  { id: "ch7_3_5", category: "Chương 7 - Bài 3", timeLimit: 30, question: "Cho tam giác có các cạnh là 3, 4, 5. Phân giác góc ứng với cạnh 4 chia cạnh đó tỉ lệ nào?", options: [{ id: "A", text: "$4/3$", isCorrect: false }, { id: "B", text: "$3/5$", isCorrect: true }, { id: "C", text: "$1/2$", isCorrect: false }, { id: "D", text: "$5/3$", isCorrect: false }] },
  { id: "ch7_3_6", category: "Chương 7 - Bài 3", timeLimit: 30, question: "Nếu $\\Delta ABC$ cân tại $A$ thì trung tuyến, phân giác ứng với $BC$ có tính chất gì?", options: [{ id: "A", text: "Không có quan hệ do cắt nhau", isCorrect: false }, { id: "B", text: "Không bằng nhau", isCorrect: false }, { id: "C", text: "Trùng nhau", isCorrect: true }, { id: "D", text: "Vuông góc nhau chéo góc", isCorrect: false }] },
  { id: "ch7_3_7", category: "Chương 7 - Bài 3", timeLimit: 30, question: "Giao điểm của ba đường phân giác trong tam giác gọi là:", options: [{ id: "A", text: "Tâm đường tròn ngoại tiếp", isCorrect: false }, { id: "B", text: "Tâm đường tròn nội tiếp", isCorrect: true }, { id: "C", text: "Trọng tâm", isCorrect: false }, { id: "D", text: "Trực tâm", isCorrect: false }] },
  { id: "ch7_3_8", category: "Chương 7 - Bài 3", timeLimit: 30, question: "Đường kính của tâm đường tròn nội tiếp tam giác luôn:", options: [{ id: "A", text: "Là phân giác", isCorrect: false }, { id: "B", text: "Qua hai đỉnh đối diện", isCorrect: false }, { id: "C", text: "Vuông góc tam giác nội", isCorrect: false }, { id: "D", text: "Tiếp xúc 3 cạnh", isCorrect: true }] },
  { id: "ch7_3_9", category: "Chương 7 - Bài 3", timeLimit: 30, question: "Khoảng cách từ tâm đường phân giác nội tiếp đến ba cạnh tam giác luôn:", options: [{ id: "A", text: "Bằng $\\frac{1}{3}$ đường cao", isCorrect: false }, { id: "B", text: "Bằng nửa chu vi", isCorrect: false }, { id: "C", text: "Bằng nhau", isCorrect: true }, { id: "D", text: "Không thể đo", isCorrect: false }] },
  { id: "ch7_3_10", category: "Chương 7 - Bài 3", timeLimit: 30, question: "Nếu hai góc có cùng phân giác mà đường phân giác chung là một đoạn thẳng thì hai phân đoạn tam giác là:", options: [{ id: "A", text: "Đồng phân giác diện", isCorrect: false }, { id: "B", text: "Đều nhau", isCorrect: false }, { id: "C", text: "Tương đương chia góc", isCorrect: true }, { id: "D", text: "Tam giác đều", isCorrect: false }] }
];
