export const questions_ch5 = [
  // Bài 1: Khái niệm hàm số (10 câu)
  { id: "ch5_1_1", category: "Chương 5 - Bài 1", timeLimit: 30, question: "Đại lượng $y$ là hàm số của đại lượng $x$ nếu:", options: [{ id: "A", text: "Với mỗi giá trị của $x$, ta xác định được nhiều giá trị của $y$", isCorrect: false }, { id: "B", text: "Với mỗi giá trị của $x$, ta xác định được duy nhất một giá trị tương ứng của $y$", isCorrect: true }, { id: "C", text: "$x$ và $y$ luôn bằng nhau", isCorrect: false }, { id: "D", text: "$x$ tỉ lệ thuận với $y$", isCorrect: false }] },
  { id: "ch5_1_2", category: "Chương 5 - Bài 1", timeLimit: 30, question: "Cho hàm số $y = f(x) = 2x - 3$. Giá trị $f(2)$ bằng:", options: [{ id: "A", text: "$1$", isCorrect: true }, { id: "B", text: "$0$", isCorrect: false }, { id: "C", text: "$-1$", isCorrect: false }, { id: "D", text: "$2$", isCorrect: false }] },
  { id: "ch5_1_3", category: "Chương 5 - Bài 1", timeLimit: 30, question: "Đại lượng $y$ có phải là hàm số của đại lượng $x$ khi bảng giá trị sau được cho: $(x;y) = (1;2), (2;3), (3;4), (1;5)$ không?", options: [{ id: "A", text: "Có", isCorrect: false }, { id: "B", text: "Không đáp án nào đúng", isCorrect: false }, { id: "C", text: "Không", isCorrect: true }, { id: "D", text: "Luôn luôn", isCorrect: false }] },
  { id: "ch5_1_4", category: "Chương 5 - Bài 1", timeLimit: 30, question: "Cho hàm số $y = x^2$. Cặp giá trị $(x; y)$ nào sau đây là đúng?", options: [{ id: "A", text: "$(-2; -4)$", isCorrect: false }, { id: "B", text: "$(2; 4)$", isCorrect: true }, { id: "C", text: "$(3; 6)$", isCorrect: false }, { id: "D", text: "$(-3; 6)$", isCorrect: false }] },
  { id: "ch5_1_5", category: "Chương 5 - Bài 1", timeLimit: 30, question: "Cho hàm số $y = f(x) = \\frac{12}{x}$. Khẳng định nào sau đây sai?", options: [{ id: "A", text: "$f(2) = 6$", isCorrect: false }, { id: "B", text: "$f(-3) = -4$", isCorrect: false }, { id: "C", text: "$f(4) = 3$", isCorrect: false }, { id: "D", text: "$f(0) = 0$", isCorrect: true }] },
  { id: "ch5_1_6", category: "Chương 5 - Bài 1", timeLimit: 30, question: "Công thức nào sau đây biểu diễn $y$ là hàm số của $x$?", options: [{ id: "A", text: "$y = 5x + 1$", isCorrect: true }, { id: "B", text: "$y^2 = x$", isCorrect: false }, { id: "C", text: "$x^2 + y^2 = 1$", isCorrect: false }, { id: "D", text: "$|y| = x$", isCorrect: false }] },
  { id: "ch5_1_7", category: "Chương 5 - Bài 1", timeLimit: 30, question: "Hàm số $y = f(x)$ được cho bởi công thức $y = -3x$. Nếu $y = 12$ thì $x$ bằng:", options: [{ id: "A", text: "$4$", isCorrect: false }, { id: "B", text: "$-36$", isCorrect: false }, { id: "C", text: "$-4$", isCorrect: true }, { id: "D", text: "$36$", isCorrect: false }] },
  { id: "ch5_1_8", category: "Chương 5 - Bài 1", timeLimit: 30, question: "Cho đại lượng $y$ phụ thuộc vào $x$ theo hệ thức $y = 0x + 5$. Khẳng định đúng là:", options: [{ id: "A", text: "$y$ không phải là hàm số của $x$", isCorrect: false }, { id: "B", text: "$y$ là hàm hằng", isCorrect: true }, { id: "C", text: "$y$ tỉ lệ thuận với $x$", isCorrect: false }, { id: "D", text: "$x$ là hàm số của $y$", isCorrect: false }] },
  { id: "ch5_1_9", category: "Chương 5 - Bài 1", timeLimit: 30, question: "Biết $y = \\frac{x-1}{2}$, khi $x = 5$ thì:", options: [{ id: "A", text: "$y = 3$", isCorrect: false }, { id: "B", text: "$y = 4$", isCorrect: false }, { id: "C", text: "$y = 1$", isCorrect: false }, { id: "D", text: "$y = 2$", isCorrect: true }] },
  { id: "ch5_1_10", category: "Chương 5 - Bài 1", timeLimit: 30, question: "Tập xác định của hàm số $y = \\frac{2}{x-3}$ là:", options: [{ id: "A", text: "$x \\neq -3$", isCorrect: false }, { id: "B", text: "$x \\neq 3$", isCorrect: true }, { id: "C", text: "$x \\neq 0$", isCorrect: false }, { id: "D", text: "$x > 3$", isCorrect: false }] },

  // Bài 2: Toạ độ của một điểm và đồ thị của hàm số (10 câu)
  { id: "ch5_2_1", category: "Chương 5 - Bài 2", timeLimit: 30, question: "Trong mặt phẳng tọa độ $Oxy$, trục hoành là:", options: [{ id: "A", text: "Trục $Ox$", isCorrect: true }, { id: "B", text: "Trục $Oy$", isCorrect: false }, { id: "C", text: "Gốc tọa độ $O$", isCorrect: false }, { id: "D", text: "Đường phân giác", isCorrect: false }] },
  { id: "ch5_2_2", category: "Chương 5 - Bài 2", timeLimit: 30, question: "Điểm $M(-2; 5)$ có tung độ là:", options: [{ id: "A", text: "$-2$", isCorrect: false }, { id: "B", text: "$5$", isCorrect: true }, { id: "C", text: "$3$", isCorrect: false }, { id: "D", text: "$-5$", isCorrect: false }] },
  { id: "ch5_2_3", category: "Chương 5 - Bài 2", timeLimit: 30, question: "Gốc tọa độ $O$ có tọa độ là:", options: [{ id: "A", text: "$(1; 1)$", isCorrect: false }, { id: "B", text: "$(0; 1)$", isCorrect: false }, { id: "C", text: "$(0; 0)$", isCorrect: true }, { id: "D", text: "$(1; 0)$", isCorrect: false }] },
  { id: "ch5_2_4", category: "Chương 5 - Bài 2", timeLimit: 30, question: "Điểm $P(0; -4)$ nằm trên:", options: [{ id: "A", text: "Trục hoành", isCorrect: false }, { id: "B", text: "Trục tung", isCorrect: true }, { id: "C", text: "Đường phân giác", isCorrect: false }, { id: "D", text: "Gốc tọa độ", isCorrect: false }] },
  { id: "ch5_2_5", category: "Chương 5 - Bài 2", timeLimit: 30, question: "Điểm $Q(3; 0)$ nằm trên:", options: [{ id: "A", text: "Trục tung", isCorrect: false }, { id: "B", text: "Gốc tọa độ", isCorrect: false }, { id: "C", text: "Trục hoành", isCorrect: true }, { id: "D", text: "Đường thẳng $y = x$", isCorrect: false }] },
  { id: "ch5_2_6", category: "Chương 5 - Bài 2", timeLimit: 30, question: "Điểm thuộc đồ thị hàm số $y = 3x - 1$ là:", options: [{ id: "A", text: "$(1; 1)$", isCorrect: false }, { id: "B", text: "$(0; 1)$", isCorrect: false }, { id: "C", text: "$(-1; -2)$", isCorrect: false }, { id: "D", text: "$(2; 5)$", isCorrect: true }] },
  { id: "ch5_2_7", category: "Chương 5 - Bài 2", timeLimit: 30, question: "Mặt phẳng tọa độ Oxy chia mặt phẳng thành mấy góc phần tư?", options: [{ id: "A", text: "4 góc phần tư", isCorrect: true }, { id: "B", text: "2 góc phần tư", isCorrect: false }, { id: "C", text: "3 góc phần tư", isCorrect: false }, { id: "D", text: "Không chia góc", isCorrect: false }] },
  { id: "ch5_2_8", category: "Chương 5 - Bài 2", timeLimit: 30, question: "Điểm $A(-3; -4)$ nằm ở góc phần tư thứ:", options: [{ id: "A", text: "I", isCorrect: false }, { id: "B", text: "II", isCorrect: false }, { id: "C", text: "III", isCorrect: true }, { id: "D", text: "IV", isCorrect: false }] },
  { id: "ch5_2_9", category: "Chương 5 - Bài 2", timeLimit: 30, question: "Đồ thị hàm số $y = 2x$ đi qua điểm nào?", options: [{ id: "A", text: "$(0; 0)$", isCorrect: true }, { id: "B", text: "$(1; 1)$", isCorrect: false }, { id: "C", text: "$(2; 2)$", isCorrect: false }, { id: "D", text: "$(-1; 2)$", isCorrect: false }] },
  { id: "ch5_2_10", category: "Chương 5 - Bài 2", timeLimit: 30, question: "Trong hệ trục tọa độ, hai điểm đối xứng qua trục hoành Ox có chung giá trị:", options: [{ id: "A", text: "Tung độ", isCorrect: false }, { id: "B", text: "Hoành độ", isCorrect: true }, { id: "C", text: "Cả tung độ và hoành độ", isCorrect: false }, { id: "D", text: "Không có", isCorrect: false }] },

  // Bài 3: Hàm số bậc nhất y = ax + b (a khác 0) (10 câu)
  { id: "ch5_3_1", category: "Chương 5 - Bài 3", timeLimit: 30, question: "Hàm số nào sau đây là hàm số bậc nhất?", options: [{ id: "A", text: "$y = 2x^2 + 1$", isCorrect: false }, { id: "B", text: "$y = \\frac{1}{x} - 3$", isCorrect: false }, { id: "C", text: "$y = -5x + 4$", isCorrect: true }, { id: "D", text: "$y = 0x + 7$", isCorrect: false }] },
  { id: "ch5_3_2", category: "Chương 5 - Bài 3", timeLimit: 30, question: "Hàm số $y = (m-2)x + 3$ là hàm số bậc nhất khi:", options: [{ id: "A", text: "$m > 2$", isCorrect: false }, { id: "B", text: "$m \\neq 2$", isCorrect: true }, { id: "C", text: "$m < 2$", isCorrect: false }, { id: "D", text: "$m = 2$", isCorrect: false }] },
  { id: "ch5_3_3", category: "Chương 5 - Bài 3", timeLimit: 30, question: "Hàm số bậc nhất $y = ax + b$ đồng biến trên $\\mathbb{R}$ khi:", options: [{ id: "A", text: "$a < 0$", isCorrect: false }, { id: "B", text: "$a > 0$", isCorrect: true }, { id: "C", text: "$a = 0$", isCorrect: false }, { id: "D", text: "$b > 0$", isCorrect: false }] },
  { id: "ch5_3_4", category: "Chương 5 - Bài 3", timeLimit: 30, question: "Hàm số $y = 4 - 3x$ là hàm số:", options: [{ id: "A", text: "Nghịch biến trên $\\mathbb{R}$", isCorrect: true }, { id: "B", text: "Đồng biến trên $\\mathbb{R}$", isCorrect: false }, { id: "C", text: "Không đổi", isCorrect: false }, { id: "D", text: "Tuần hoàn", isCorrect: false }] },
  { id: "ch5_3_5", category: "Chương 5 - Bài 3", timeLimit: 30, question: "Đồ thị hàm số bậc nhất $y = ax + b$ với $a \\neq 0$ là:", options: [{ id: "A", text: "Đường cong", isCorrect: false }, { id: "B", text: "Đường tròn", isCorrect: false }, { id: "C", text: "Đường thẳng", isCorrect: true }, { id: "D", text: "Điểm", isCorrect: false }] },
  { id: "ch5_3_6", category: "Chương 5 - Bài 3", timeLimit: 30, question: "Đồ thị hàm số $y = 2x - 4$ cắt trục tung Oy tại điểm:", options: [{ id: "A", text: "$(0; -4)$", isCorrect: true }, { id: "B", text: "$(-4; 0)$", isCorrect: false }, { id: "C", text: "$(2; 0)$", isCorrect: false }, { id: "D", text: "$(0; 2)$", isCorrect: false }] },
  { id: "ch5_3_7", category: "Chương 5 - Bài 3", timeLimit: 30, question: "Đồ thị hàm số $y = x + 3$ cắt trục hoành Ox tại điểm:", options: [{ id: "A", text: "$(0; 3)$", isCorrect: false }, { id: "B", text: "$(3; 0)$", isCorrect: false }, { id: "C", text: "$(-3; 0)$", isCorrect: true }, { id: "D", text: "$(0; -3)$", isCorrect: false }] },
  { id: "ch5_3_8", category: "Chương 5 - Bài 3", timeLimit: 30, question: "Cho hai hàm số $y = (2m+1)x - 3$. Hàm số nghịch biến khi:", options: [{ id: "A", text: "$m > -\\frac{1}{2}$", isCorrect: false }, { id: "B", text: "$m < -\\frac{1}{2}$", isCorrect: true }, { id: "C", text: "$m = -\\frac{1}{2}$", isCorrect: false }, { id: "D", text: "$m < 0$", isCorrect: false }] },
  { id: "ch5_3_9", category: "Chương 5 - Bài 3", timeLimit: 30, question: "Đồ thị của hàm số $y = ax + b$ song song với đường thẳng $y = 5x$ khi:", options: [{ id: "A", text: "$a = 5, b = 0$", isCorrect: false }, { id: "B", text: "$a \\neq 5$", isCorrect: false }, { id: "C", text: "$a = 5, b \\neq 0$", isCorrect: true }, { id: "D", text: "$a = -5, b \\neq 0$", isCorrect: false }] },
  { id: "ch5_3_10", category: "Chương 5 - Bài 3", timeLimit: 30, question: "Hai đường thẳng $y = 2x - 1$ và $y = 2x + 3$ có vị trí tương đối là:", options: [{ id: "A", text: "Cắt nhau", isCorrect: false }, { id: "B", text: "Trùng nhau", isCorrect: false }, { id: "C", text: "Vuông góc", isCorrect: false }, { id: "D", text: "Song song", isCorrect: true }] },

  // Bài 4: Hệ số góc của đường thẳng (10 câu)
  { id: "ch5_4_1", category: "Chương 5 - Bài 4", timeLimit: 30, question: "Hệ số góc của đường thẳng $y = -7x + 2$ là:", options: [{ id: "A", text: "$2$", isCorrect: false }, { id: "B", text: "$-7$", isCorrect: true }, { id: "C", text: "$7$", isCorrect: false }, { id: "D", text: "$-2$", isCorrect: false }] },
  { id: "ch5_4_2", category: "Chương 5 - Bài 4", timeLimit: 30, question: "Đường thẳng tạo với chiều dương trục Ox một góc nhọn khi:", options: [{ id: "A", text: "Hệ số góc $a < 0$", isCorrect: false }, { id: "B", text: "Hệ số góc $a = 0$", isCorrect: false }, { id: "C", text: "Hệ số góc $a > 0$", isCorrect: true }, { id: "D", text: "Tung độ gốc $b > 0$", isCorrect: false }] },
  { id: "ch5_4_3", category: "Chương 5 - Bài 4", timeLimit: 30, question: "Đường thẳng tạo với chiều dương trục Ox một góc tù khi:", options: [{ id: "A", text: "Hệ số góc $a > 0$", isCorrect: false }, { id: "B", text: "Hệ số góc $a < 0$", isCorrect: true }, { id: "C", text: "Hệ số góc $a = 0$", isCorrect: false }, { id: "D", text: "Tung độ gốc $b < 0$", isCorrect: false }] },
  { id: "ch5_4_4", category: "Chương 5 - Bài 4", timeLimit: 30, question: "Xác định hệ số góc $a$ của đường thẳng đi qua gốc tọa độ và điểm $A(1; 3)$:", options: [{ id: "A", text: "$a = 1$", isCorrect: false }, { id: "B", text: "$a = -3$", isCorrect: false }, { id: "C", text: "$a = 3$", isCorrect: true }, { id: "D", text: "$a = \\frac{1}{3}$", isCorrect: false }] },
  { id: "ch5_4_5", category: "Chương 5 - Bài 4", timeLimit: 30, question: "Đường thẳng $y = x - 5$ tạo với chiều dương Ox một góc:", options: [{ id: "A", text: "$45^\\circ$", isCorrect: true }, { id: "B", text: "$90^\\circ$", isCorrect: false }, { id: "C", text: "$30^\\circ$", isCorrect: false }, { id: "D", text: "$60^\\circ$", isCorrect: false }] },
  { id: "ch5_4_6", category: "Chương 5 - Bài 4", timeLimit: 30, question: "Đường thẳng có hệ số góc bằng $-1$ và đi qua điểm $(0; 2)$ có phương trình là:", options: [{ id: "A", text: "$y = x + 2$", isCorrect: false }, { id: "B", text: "$y = -x - 2$", isCorrect: false }, { id: "C", text: "$y = -x + 2$", isCorrect: true }, { id: "D", text: "$y = 2x - 1$", isCorrect: false }] },
  { id: "ch5_4_7", category: "Chương 5 - Bài 4", timeLimit: 30, question: "Hai đường thẳng $y = ax + b$ và $y = a'x + b'$ cắt nhau khi:", options: [{ id: "A", text: "$a = a', b = b'$", isCorrect: false }, { id: "B", text: "$a \\neq a'$", isCorrect: true }, { id: "C", text: "$a = a', b \\neq b'$", isCorrect: false }, { id: "D", text: "$a \\cdot a' = -1$", isCorrect: false }] },
  { id: "ch5_4_8", category: "Chương 5 - Bài 4", timeLimit: 30, question: "Giá trị của $m$ để đường thẳng $y = mx + 1$ song song với $y = 3x - 5$ là:", options: [{ id: "A", text: "$m = -3$", isCorrect: false }, { id: "B", text: "$m = 0$", isCorrect: false }, { id: "C", text: "$m = 3$", isCorrect: true }, { id: "D", text: "$m = 1$", isCorrect: false }] },
  { id: "ch5_4_9", category: "Chương 5 - Bài 4", timeLimit: 30, question: "Giao điểm của hai đường thẳng $y = 2x$ và $y = -x + 3$ là:", options: [{ id: "A", text: "$(1; 2)$", isCorrect: true }, { id: "B", text: "$(2; 1)$", isCorrect: false }, { id: "C", text: "$(1; 1)$", isCorrect: false }, { id: "D", text: "$(-1; -2)$", isCorrect: false }] },
  { id: "ch5_4_10", category: "Chương 5 - Bài 4", timeLimit: 30, question: "Một tam giác vuông có hai cạnh góc vuông nằm trên hai trục tọa độ. Đường thẳng chứa cạnh huyền có phương trình $y = -x + 4$. Diện tích tam giác đó là:", options: [{ id: "A", text: "$4$", isCorrect: false }, { id: "B", text: "$16$", isCorrect: false }, { id: "C", text: "$8$", isCorrect: true }, { id: "D", text: "$12$", isCorrect: false }] }
];
