export const questions_ch6 = [
  // Bài 1: Phương trình bậc nhất một ẩn (10 câu)
  { id: "ch6_1_1", category: "Chương 6 - Bài 1", timeLimit: 30, question: "Phương trình nào sau đây là phương trình bậc nhất một ẩn?", options: [{ id: "A", text: "$2x^2 + 1 = 0$", isCorrect: false }, { id: "B", text: "$0x - 5 = 0$", isCorrect: false }, { id: "C", text: "$3x - 4 = 0$", isCorrect: true }, { id: "D", text: "$\\frac{1}{x} + 2 = 0$", isCorrect: false }] },
  { id: "ch6_1_2", category: "Chương 6 - Bài 1", timeLimit: 30, question: "Nghiệm của phương trình $2x - 6 = 0$ là:", options: [{ id: "A", text: "$x = 3$", isCorrect: true }, { id: "B", text: "$x = -3$", isCorrect: false }, { id: "C", text: "$x = 6$", isCorrect: false }, { id: "D", text: "$x = -6$", isCorrect: false }] },
  { id: "ch6_1_3", category: "Chương 6 - Bài 1", timeLimit: 30, question: "Khẳng định nào đúng khi giải phương trình $ax + b = 0$ $(a \\neq 0)$?", options: [{ id: "A", text: "$x = \\frac{b}{a}$", isCorrect: false }, { id: "B", text: "$x = -\\frac{a}{b}$", isCorrect: false }, { id: "C", text: "$x = -\\frac{b}{a}$", isCorrect: true }, { id: "D", text: "Phương trình vô nghiệm", isCorrect: false }] },
  { id: "ch6_1_4", category: "Chương 6 - Bài 1", timeLimit: 30, question: "Giá trị $x = -2$ là nghiệm của phương trình nào?", options: [{ id: "A", text: "$x - 2 = 0$", isCorrect: false }, { id: "B", text: "$2x + 4 = 0$", isCorrect: true }, { id: "C", text: "$3x - 6 = 0$", isCorrect: false }, { id: "D", text: "$-x + 2 = 0$", isCorrect: false }] },
  { id: "ch6_1_5", category: "Chương 6 - Bài 1", timeLimit: 30, question: "Giải phương trình $5 - 2x = x + 11$ ta được nghiệm là:", options: [{ id: "A", text: "$x = -2$", isCorrect: true }, { id: "B", text: "$x = 2$", isCorrect: false }, { id: "C", text: "$x = 3$", isCorrect: false }, { id: "D", text: "$x = -3$", isCorrect: false }] },
  { id: "ch6_1_6", category: "Chương 6 - Bài 1", timeLimit: 30, question: "Tập nghiệm của phương trình $0x = 5$ là:", options: [{ id: "A", text: "$S = \\{0\\}$", isCorrect: false }, { id: "B", text: "$S = \\mathbb{R}$", isCorrect: false }, { id: "C", text: "$S = \\{5\\}$", isCorrect: false }, { id: "D", text: "$S = \\emptyset$", isCorrect: true }] },
  { id: "ch6_1_7", category: "Chương 6 - Bài 1", timeLimit: 30, question: "Tập nghiệm của phương trình $0x = 0$ là:", options: [{ id: "A", text: "$S = \\emptyset$", isCorrect: false }, { id: "B", text: "$S = \\mathbb{R}$", isCorrect: true }, { id: "C", text: "$S = \\{0\\}$", isCorrect: false }, { id: "D", text: "$S = \\{1\\}$", isCorrect: false }] },
  { id: "ch6_1_8", category: "Chương 6 - Bài 1", timeLimit: 30, question: "Nghiệm của phương trình $\\frac{x}{2} - 1 = 3$ là:", options: [{ id: "A", text: "$x = 4$", isCorrect: false }, { id: "B", text: "$x = 6$", isCorrect: false }, { id: "C", text: "$x = 8$", isCorrect: true }, { id: "D", text: "$x = 2$", isCorrect: false }] },
  { id: "ch6_1_9", category: "Chương 6 - Bài 1", timeLimit: 30, question: "Phương trình $x^2 = 4$ có tương đương với phương trình $x = 2$ không?", options: [{ id: "A", text: "Có", isCorrect: false }, { id: "B", text: "Chỉ khi $x > 0$", isCorrect: false }, { id: "C", text: "Không", isCorrect: true }, { id: "D", text: "Chưa đủ dữ kiện", isCorrect: false }] },
  { id: "ch6_1_10", category: "Chương 6 - Bài 1", timeLimit: 30, question: "Nghiệm của phương trình $3(x - 2) = 2x + 1$ là:", options: [{ id: "A", text: "$x = 5$", isCorrect: false }, { id: "B", text: "$x = 7$", isCorrect: true }, { id: "C", text: "$x = 3$", isCorrect: false }, { id: "D", text: "$x = -7$", isCorrect: false }] },

  // Bài 2: Giải bài toán bằng cách lập phương trình bậc nhất (10 câu)
  { id: "ch6_2_1", category: "Chương 6 - Bài 2", timeLimit: 30, question: "Lan mua 5 quyển vở, Minh mua 3 quyển loại đó. Lan trả nhiều hơn Minh 14 nghìn đồng. Giá một quyển vở là:", options: [{ id: "A", text: "7 nghìn đồng", isCorrect: true }, { id: "B", text: "6 nghìn đồng", isCorrect: false }, { id: "C", text: "5 nghìn đồng", isCorrect: false }, { id: "D", text: "8 nghìn đồng", isCorrect: false }] },
  { id: "ch6_2_2", category: "Chương 6 - Bài 2", timeLimit: 30, question: "Năm nay tuổi mẹ gấp 3 lần tuổi con. 5 năm nữa tổng số tuổi của hai mẹ con là 50. Tuổi con hiện nay là:", options: [{ id: "A", text: "15", isCorrect: false }, { id: "B", text: "10", isCorrect: true }, { id: "C", text: "5", isCorrect: false }, { id: "D", text: "12", isCorrect: false }] },
  { id: "ch6_2_3", category: "Chương 6 - Bài 2", timeLimit: 30, question: "Một ô tô đi từ A đến B với vận tốc $40$ km/h. Lúc về đi tốc độ $50$ km/h. Thời gian đi nhiều hơn lúc về là 1 giờ. Quãng đường AB dài:", options: [{ id: "A", text: "150 km", isCorrect: false }, { id: "B", text: "180 km", isCorrect: false }, { id: "C", text: "200 km", isCorrect: true }, { id: "D", text: "220 km", isCorrect: false }] },
  { id: "ch6_2_4", category: "Chương 6 - Bài 2", timeLimit: 30, question: "Hai người cùng làm chung một công việc thì xong trong 6 ngày. Người thứ nhất làm một mình thì xong trong 10 ngày. Tính xem người thứ hai làm xong trong mấy ngày?", options: [{ id: "A", text: "14 ngày", isCorrect: false }, { id: "B", text: "15 ngày", isCorrect: true }, { id: "C", text: "16 ngày", isCorrect: false }, { id: "D", text: "12 ngày", isCorrect: false }] },
  { id: "ch6_2_5", category: "Chương 6 - Bài 2", timeLimit: 30, question: "Tổng của hai số tự nhiên là 75. Số lớn hơn số bé 15 đơn vị. Hai số đó là:", options: [{ id: "A", text: "40 và 35", isCorrect: false }, { id: "B", text: "50 và 25", isCorrect: false }, { id: "C", text: "45 và 30", isCorrect: true }, { id: "D", text: "55 và 20", isCorrect: false }] },
  { id: "ch6_2_6", category: "Chương 6 - Bài 2", timeLimit: 30, question: "Một số có hai chữ số, chữ số hàng chục gấp đôi chữ số hàng đơn vị. Tổng các chữ số là 9. Số đó là:", options: [{ id: "A", text: "36", isCorrect: false }, { id: "B", text: "81", isCorrect: false }, { id: "C", text: "45", isCorrect: false }, { id: "D", text: "63", isCorrect: true }] },
  { id: "ch6_2_7", category: "Chương 6 - Bài 2", timeLimit: 30, question: "Lúc 7 giờ sáng một xe máy đi từ A với v = $30$ km/h. Đến 8 giờ một ô tô cũng đi từ A đuổi theo với v = $40$ km/h. Hai xe gặp nhau lúc:", options: [{ id: "A", text: "10 giờ", isCorrect: false }, { id: "B", text: "11 giờ", isCorrect: true }, { id: "C", text: "12 giờ", isCorrect: false }, { id: "D", text: "9 giờ", isCorrect: false }] },
  { id: "ch6_2_8", category: "Chương 6 - Bài 2", timeLimit: 30, question: "Hai lớp 8A và 8B trồng được 120 cây. 8A trồng nhiều hơn 8B 20 cây. 8B trồng được bao nhiêu cây?", options: [{ id: "A", text: "50 cây", isCorrect: true }, { id: "B", text: "60 cây", isCorrect: false }, { id: "C", text: "70 cây", isCorrect: false }, { id: "D", text: "40 cây", isCorrect: false }] },
  { id: "ch6_2_9", category: "Chương 6 - Bài 2", timeLimit: 30, question: "Ba lớp rủ nhau mua sách. Lớp 8A mua $\\frac{1}{3}$ tổng số, 8B mua $\\frac{1}{4}$ tổng số, 8C mua 50 quyển. Tổng số sách là:", options: [{ id: "A", text: "150", isCorrect: false }, { id: "B", text: "100", isCorrect: false }, { id: "C", text: "120", isCorrect: true }, { id: "D", text: "80", isCorrect: false }] },
  { id: "ch6_2_10", category: "Chương 6 - Bài 2", timeLimit: 30, question: "Tìm chu vi hình chữ nhật biết chiều dài hơn chiều rộng 5m và diện tích là $36m^2$ (với các chiều là số nguyên dương).", options: [{ id: "A", text: "30m", isCorrect: false }, { id: "B", text: "26m", isCorrect: true }, { id: "C", text: "24m", isCorrect: false }, { id: "D", text: "20m", isCorrect: false }] },

  // Bài tập cuối chương 6 (10 câu bù cho độ phủ bài tập)
  { id: "ch6_3_1", category: "Chương 6 - Ôn tập", timeLimit: 30, question: "Nghiệm của phương trình $2(x+1) - 3(2x-5) = 4$ là:", options: [{ id: "A", text: "$x = 3.25$", isCorrect: true }, { id: "B", text: "$x = 4$", isCorrect: false }, { id: "C", text: "$x = 1$", isCorrect: false }, { id: "D", text: "$x = -3.25$", isCorrect: false }] },
  { id: "ch6_3_2", category: "Chương 6 - Ôn tập", timeLimit: 30, question: "Phương trình $(x-2)(x+3) = 0$ có tập nghiệm là:", options: [{ id: "A", text: "$S = \\{-2; 3\\}$", isCorrect: false }, { id: "B", text: "$S = \\{2\\}$", isCorrect: false }, { id: "C", text: "$S = \\{-3\\}$", isCorrect: false }, { id: "D", text: "$S = \\{2; -3\\}$", isCorrect: true }] },
  { id: "ch6_3_3", category: "Chương 6 - Ôn tập", timeLimit: 30, question: "Hai phương trình được gọi là tương đương khi:", options: [{ id: "A", text: "Có cùng số nghiệm", isCorrect: false }, { id: "B", text: "Chung dạng đại số", isCorrect: false }, { id: "C", text: "Có cùng một tập nghiệm", isCorrect: true }, { id: "D", text: "Có thể rút gọn cho nhau", isCorrect: false }] },
  { id: "ch6_3_4", category: "Chương 6 - Ôn tập", timeLimit: 30, question: "Tìm $m$ để phương trình $mx - 4 = 2x + 1$ vô nghiệm.", options: [{ id: "A", text: "$m = 0$", isCorrect: false }, { id: "B", text: "$m = 2$", isCorrect: true }, { id: "C", text: "$m = -4$", isCorrect: false }, { id: "D", text: "$m = -2$", isCorrect: false }] },
  { id: "ch6_3_5", category: "Chương 6 - Ôn tập", timeLimit: 30, question: "Nghiệm của phương trình $\\frac{x}{3} - \\frac{x-1}{2} = 1$ là:", options: [{ id: "A", text: "$x = -5$", isCorrect: false }, { id: "B", text: "$x = -3$", isCorrect: true }, { id: "C", text: "$x = 5$", isCorrect: false }, { id: "D", text: "$x = 3$", isCorrect: false }] },
  { id: "ch6_3_6", category: "Chương 6 - Ôn tập", timeLimit: 30, question: "Thùng thứ nhất chứa nhiều hơn thùng thứ hai 15 lít dầu. Tổng hai thùng có 45 lít. Thùng lớn có:", options: [{ id: "A", text: "20 lít", isCorrect: false }, { id: "B", text: "30 lít", isCorrect: true }, { id: "C", text: "15 lít", isCorrect: false }, { id: "D", text: "35 lít", isCorrect: false }] },
  { id: "ch6_3_7", category: "Chương 6 - Ôn tập", timeLimit: 30, question: "Tìm $x$ biết $x^2 - x = 0$", options: [{ id: "A", text: "$x=0$ hoặc $x=1$", isCorrect: true }, { id: "B", text: "$x = -1$", isCorrect: false }, { id: "C", text: "$x = 1$", isCorrect: false }, { id: "D", text: "Vô nghiệm", isCorrect: false }] },
  { id: "ch6_3_8", category: "Chương 6 - Ôn tập", timeLimit: 30, question: "Một người thợ dệt 15 m vải mất 3 ngày. Cũng năng suất đó, dệt 40 m vải mất:", options: [{ id: "A", text: "5 ngày", isCorrect: false }, { id: "B", text: "6 ngày", isCorrect: false }, { id: "C", text: "8 ngày", isCorrect: true }, { id: "D", text: "7 ngày", isCorrect: false }] },
  { id: "ch6_3_9", category: "Chương 6 - Ôn tập", timeLimit: 30, question: "Có mấy bước cơ bản để giải bài toán bằng cách lập phương trình?", options: [{ id: "A", text: "2 bước", isCorrect: false }, { id: "B", text: "4 bước", isCorrect: false }, { id: "C", text: "3 bước", isCorrect: true }, { id: "D", text: "1 bước", isCorrect: false }] },
  { id: "ch6_3_10", category: "Chương 6 - Ôn tập", timeLimit: 30, question: "Cho $\\frac{x - 3}{4} = \\frac{-x + 7}{2}$, giá trị $x$ là:", options: [{ id: "A", text: "$x = \\frac{17}{3}$", isCorrect: true }, { id: "B", text: "$x = 4$", isCorrect: false }, { id: "C", text: "$x = 5$", isCorrect: false }, { id: "D", text: "$x = 3$", isCorrect: false }] }
];
