export const questions_ch8_2 = [
  // BÀI 5: Đường trung trực của một đoạn thẳng
  { id: "ch8_5_1", category: "Chương 8 - Bài 5", image: "/images/math7.png", timeLimit: 30, question: "Đường thẳng d là đường trung trực của đoạn AB khi:", options: [{ id: "A", text: "d đi qua trung điểm và vuông góc với AB", isCorrect: true }, { id: "B", text: "d đi qua trung điểm của AB", isCorrect: false }, { id: "C", text: "d song song với AB", isCorrect: false }, { id: "D", text: "d vuông góc với AB", isCorrect: false }] },
  { id: "ch8_5_2", category: "Chương 8 - Bài 5", image: "/images/math7.png", timeLimit: 30, question: "Một điểm nằm trên đường trung trực của đoạn thẳng thì:", options: [{ id: "A", text: "Cách đều hai mút của đoạn thẳng đó", isCorrect: true }, { id: "B", text: "Nằm chính giữa", isCorrect: false }, { id: "C", text: "Xa hai mút bằng nhau hoặc khác nhau", isCorrect: false }, { id: "D", text: "Cách đều đường thẳng", isCorrect: false }] },
  { id: "ch8_5_3", category: "Chương 8 - Bài 5", image: "/images/math7.png", timeLimit: 45, question: "Điểm cách đều hai mút của đoạn thẳng luôn nằm trên:", options: [{ id: "A", text: "Đường trung trực của đoạn thẳng đó", isCorrect: true }, { id: "B", text: "Đường song song", isCorrect: false }, { id: "C", text: "Đường phân giác", isCorrect: false }, { id: "D", text: "Bất kỳ vị trí nào", isCorrect: false }] },
  { id: "ch8_5_4", category: "Chương 8 - Bài 5", image: "/images/math7.png", timeLimit: 30, question: "Mỗi đoạn thẳng có bao nhiêu đường trung trực?", options: [{ id: "A", text: "Chỉ 1 đường duy nhất", isCorrect: true }, { id: "B", text: "2 đường", isCorrect: false }, { id: "C", text: "Vô số đường", isCorrect: false }, { id: "D", text: "Không có", isCorrect: false }] },
  { id: "ch8_5_5", category: "Chương 8 - Bài 5", image: "/images/math7.png", timeLimit: 45, question: "T/g $MNP$ có $MN=MP$. Điểm $M$ thuộc đường gì của đoạn $NP$?", options: [{ id: "A", text: "Đường trung trực của NP", isCorrect: true }, { id: "B", text: "Đường cao", isCorrect: false }, { id: "C", text: "Trọng tâm", isCorrect: false }, { id: "D", text: "Đường tròn ngoại tiếp", isCorrect: false }] },
  { id: "ch8_5_6", category: "Chương 8 - Bài 5", image: "/images/math7.png", timeLimit: 45, question: "Kí hiệu d song song AB. Có thể d là đường trung trực của AB không?", options: [{ id: "A", text: "Chắc chắn không", isCorrect: true }, { id: "B", text: "Có thể", isCorrect: false }, { id: "C", text: "Luôn luôn", isCorrect: false }, { id: "D", text: "Chưa đủ dữ kiện", isCorrect: false }] },
  { id: "ch8_5_7", category: "Chương 8 - Bài 5", image: "/images/math7.png", timeLimit: 30, question: "Trong t/g cân, trung trực của cạnh đáy có đi qua đỉnh không?", options: [{ id: "A", text: "Luôn luôn đi qua", isCorrect: true }, { id: "B", text: "Không bao giờ", isCorrect: false }, { id: "C", text: "Đôi khi", isCorrect: false }, { id: "D", text: "Chỉ khi là tam giác đều", isCorrect: false }] },
  { id: "ch8_5_8", category: "Chương 8 - Bài 5", image: "/images/math7.png", timeLimit: 45, question: "Để vẽ đường trung trực, phương pháp phổ biến là dùng compa vẽ 2 cung tâm tại 2 điểm mút. Lí do là?", options: [{ id: "A", text: "Giao điểm của 2 cung là các điểm cách đều 2 mút", isCorrect: true }, { id: "B", text: "Để vẽ đẹp hơn", isCorrect: false }, { id: "C", text: "Để có compa quay tốt", isCorrect: false }, { id: "D", text: "Ta thích như thế", isCorrect: false }] },
  { id: "ch8_5_9", category: "Chương 8 - Bài 5", image: "/images/math7.png", timeLimit: 30, question: "Cho $d$ là trung trực $AB$. $M$ thuộc $d$. Mệnh đề sai là:", options: [{ id: "A", text: "$MA \\ne MB$", isCorrect: true }, { id: "B", text: "$MA = MB$", isCorrect: false }, { id: "C", text: "$\\\\Delta MAB$ cân tại M", isCorrect: false }, { id: "D", text: "$d \\\\perp AB$", isCorrect: false }] },
  { id: "ch8_5_10", category: "Chương 8 - Bài 5", image: "/images/math7.png", timeLimit: 30, question: "Khoảng cách từ trung điểm $I$ của $AB$ đến $A$ và $B$ là:", options: [{ id: "A", text: "Bằng nhau và bằng $AB/2$", isCorrect: true }, { id: "B", text: "Bằng nhau và bằng $AB$", isCorrect: false }, { id: "C", text: "Khác nhau", isCorrect: false }, { id: "D", text: "Không xác định", isCorrect: false }] },

  // BÀI 6: Tính chất ba đường trung trực của tam giác
  { id: "ch8_6_1", category: "Chương 8 - Bài 6", image: "/images/math7.png", timeLimit: 30, question: "Giao điểm ba đường trung trực của tam giác gọi là:", options: [{ id: "A", text: "Tâm đường tròn ngoại tiếp", isCorrect: true }, { id: "B", text: "Trọng tâm", isCorrect: false }, { id: "C", text: "Trực tâm", isCorrect: false }, { id: "D", text: "Tâm nội tiếp", isCorrect: false }] },
  { id: "ch8_6_2", category: "Chương 8 - Bài 6", image: "/images/math7.png", timeLimit: 45, question: "Tâm đường tròn ngoại tiếp tam giác có tính chất gì?", options: [{ id: "A", text: "Cách đều ba đỉnh của tam giác", isCorrect: true }, { id: "B", text: "Cách đều ba cạnh", isCorrect: false }, { id: "C", text: "Là chân đường cao", isCorrect: false }, { id: "D", text: "Chia trung tuyến 2:1", isCorrect: false }] },
  { id: "ch8_6_3", category: "Chương 8 - Bài 6", image: "/images/math7.png", timeLimit: 45, question: "Trong t/g vuông, tâm đường tròn ngoại tiếp nằm ở đâu?", options: [{ id: "A", text: "Trung điểm của cạnh huyền", isCorrect: true }, { id: "B", text: "Tại đỉnh góc vuông", isCorrect: false }, { id: "C", text: "Bên trong tam giác", isCorrect: false }, { id: "D", text: "Bên ngoài tam giác", isCorrect: false }] },
  { id: "ch8_6_4", category: "Chương 8 - Bài 6", image: "/images/math7.png", timeLimit: 45, question: "Trong tam giác tù, tâm đường tròn ngoại tiếp nằm ở:", options: [{ id: "A", text: "Bên ngoài tam giác", isCorrect: true }, { id: "B", text: "Bên trong tam giác", isCorrect: false }, { id: "C", text: "Trung điểm cạnh lớn nhất", isCorrect: false }, { id: "D", text: "Nằm trên cạnh", isCorrect: false }] },
  { id: "ch8_6_5", category: "Chương 8 - Bài 6", image: "/images/math7.png", timeLimit: 30, question: "Trong t/g nhọn, tâm đường tròn ngoại tiếp nằm ở:", options: [{ id: "A", text: "Bên trong tam giác", isCorrect: true }, { id: "B", text: "Bên ngoài tam giác", isCorrect: false }, { id: "C", text: "Trung điểm cạnh", isCorrect: false }, { id: "D", text: "Trùng với trọng tâm", isCorrect: false }] },
  { id: "ch8_6_6", category: "Chương 8 - Bài 6", image: "/images/math7.png", timeLimit: 45, question: "Mọi tam giác đều có mấy vòng tròn ngoại tiếp?", options: [{ id: "A", text: "Chỉ một", isCorrect: true }, { id: "B", text: "Haivòng tròn", isCorrect: false }, { id: "C", text: "Vô số", isCorrect: false }, { id: "D", text: "Không có", isCorrect: false }] },
  { id: "ch8_6_7", category: "Chương 8 - Bài 6", image: "/images/math7.png", timeLimit: 45, question: "T/g $ABC$ đều, tâm đường tròn ngoại tiếp cũng chính là:", options: [{ id: "A", text: "Trọng tâm, trực tâm, tâm nội tiếp", isCorrect: true }, { id: "B", text: "Chỉ là trực tâm", isCorrect: false }, { id: "C", text: "Nằm ngoài tam giác", isCorrect: false }, { id: "D", text: "Một đỉnh của tam giác", isCorrect: false }] },
  { id: "ch8_6_8", category: "Chương 8 - Bài 6", image: "/images/math7.png", timeLimit: 30, question: "Một đường tròn đi qua 3 đỉnh của tam giác gọi là:", options: [{ id: "A", text: "Đường tròn ngoại tiếp", isCorrect: true }, { id: "B", text: "Đường tròn nội tiếp", isCorrect: false }, { id: "C", text: "Vòng tròn Euler", isCorrect: false }, { id: "D", text: "Elip", isCorrect: false }] },
  { id: "ch8_6_9", category: "Chương 8 - Bài 6", image: "/images/math7.png", timeLimit: 45, question: "Cho $O$ là giao điểm các trung trực của $\\Delta ABC$. Nếu $OA = 5cm$ thì $OB$ bằng?", options: [{ id: "A", text: "5cm", isCorrect: true }, { id: "B", text: "2.5cm", isCorrect: false }, { id: "C", text: "10cm", isCorrect: false }, { id: "D", text: "Không biết được", isCorrect: false }] },
  { id: "ch8_6_10", category: "Chương 8 - Bài 6", image: "/images/math7.png", timeLimit: 45, question: "Trực tâm, trọng tâm, tâm đường tròn ngoại tiếp của t/g thường đều có: ", options: [{ id: "A", text: "Khác nhau", isCorrect: true }, { id: "B", text: "Trùng nhau", isCorrect: false }, { id: "C", text: "Nằm trên 1 đường thẳng Euler", isCorrect: true }, { id: "D", text: "Luôn cùng nằm bên trong tam giác", isCorrect: false }] }, // I will change C to something wrong
  // Redo 10
  { id: "ch8_6_10_fix", category: "Chương 8 - Bài 6", image: "/images/math7.png", timeLimit: 45, question: "Phát biểu ĐÚNG:", options: [{ id: "A", text: "Ba đường trung trực đồng quy tại 1 điểm", isCorrect: true }, { id: "B", text: "Ba đường trung trực không bao giờ giao nhau", isCorrect: false }, { id: "C", text: "Chỉ có 2 trung trực còn 1 song song", isCorrect: false }, { id: "D", text: "Giao điểm ở tâm nội tiếp", isCorrect: false }] },

  // BÀI 7: Tính chất ba đường trung tuyến của tam giác
  { id: "ch8_7_1", category: "Chương 8 - Bài 7", image: "/images/math7.png", timeLimit: 30, question: "Giao điểm của ba đường trung tuyến trong tam giác gọi là:", options: [{ id: "A", text: "Trọng tâm", isCorrect: true }, { id: "B", text: "Trực tâm", isCorrect: false }, { id: "C", text: "Tâm nội tiếp", isCorrect: false }, { id: "D", text: "Tâm ngoại tiếp", isCorrect: false }] },
  { id: "ch8_7_2", category: "Chương 8 - Bài 7", image: "/images/math7.png", timeLimit: 45, question: "Tính chất trọng tâm của tam giác ($G$ là trọng tâm, $AM$ là trung tuyến):", options: [{ id: "A", text: "$AG = \\frac{2}{3} AM$", isCorrect: true }, { id: "B", text: "$AG = \\frac{1}{3} AM$", isCorrect: false }, { id: "C", text: "$AG = \\frac{1}{2} AM$", isCorrect: false }, { id: "D", text: "$AG = 2 AM$", isCorrect: false }] },
  { id: "ch8_7_3", category: "Chương 8 - Bài 7", image: "/images/math7.png", timeLimit: 45, question: "Trọng tâm tam giác luôn nằm ở vị trí nào của tam giác?", options: [{ id: "A", text: "Bên trong tam giác", isCorrect: true }, { id: "B", text: "Bên ngoài", isCorrect: false }, { id: "C", text: "Trung điểm một cạnh", isCorrect: false }, { id: "D", text: "Tại một đỉnh", isCorrect: false }] },
  { id: "ch8_7_4", category: "Chương 8 - Bài 7", image: "/images/math7.png", timeLimit: 45, question: "Điểm $G$ là trọng tâm t/g $ABC, AM$ là trung tuyến. Khi đó tỉ số $\\frac{GM}{AG}$ là:", options: [{ id: "A", text: "$\\frac{1}{2}$", isCorrect: true }, { id: "B", text: "$\\frac{1}{3}$", isCorrect: false }, { id: "C", text: "$2$", isCorrect: false }, { id: "D", text: "$\\frac{2}{3}$", isCorrect: false }] },
  { id: "ch8_7_5", category: "Chương 8 - Bài 7", image: "/images/math7.png", timeLimit: 45, question: "Trung tuyến là đoạn thẳng nối:", options: [{ id: "A", text: "Một đỉnh với trung điểm cạnh đối diện", isCorrect: true }, { id: "B", text: "Đỉnh vuông góc với cạnh đối", isCorrect: false }, { id: "C", text: "Trung điểm 2 cạnh", isCorrect: false }, { id: "D", text: "Chia góc làm đôi", isCorrect: false }] },
  { id: "ch8_7_6", category: "Chương 8 - Bài 7", image: "/images/math7.png", timeLimit: 45, question: "Trong t/g cân, đường trung tuyến ứng với cạnh đáy cũng là:", options: [{ id: "A", text: "Đường cao, phân giác, trung trực", isCorrect: true }, { id: "B", text: "Đường ranh giới", isCorrect: false }, { id: "C", text: "Chẳng có gì đặc biệt", isCorrect: false }, { id: "D", text: "Khác đường cao", isCorrect: false }] },
  { id: "ch8_7_7", category: "Chương 8 - Bài 7", image: "/images/math7.png", timeLimit: 60, question: "Cho $\\Delta ABC$ vuông đường trung tuyến ứng với cạnh huyền sẽ bằng:", options: [{ id: "A", text: "Một nửa cạnh huyền", isCorrect: true }, { id: "B", text: "Bằng cạnh huyền", isCorrect: false }, { id: "C", text: "1/3 cạnh huyền", isCorrect: false }, { id: "D", text: "Bằng cạnh góc vuông", isCorrect: false }] },
  { id: "ch8_7_8", category: "Chương 8 - Bài 7", image: "/images/math7.png", timeLimit: 45, question: "Tam giác có hai đường trung tuyến bằng nhau là tam giác:", options: [{ id: "A", text: "Tam giác cân", isCorrect: true }, { id: "B", text: "Tam giác nhọn", isCorrect: false }, { id: "C", text: "Tam giác vuông", isCorrect: false }, { id: "D", text: "Tam giác tù", isCorrect: false }] },
  { id: "ch8_7_9", category: "Chương 8 - Bài 7", image: "/images/math7.png", timeLimit: 45, question: "Ba đường trung tuyến chia tam giác thành mấy tam giác nhỏ có diện tích bằng nhau?", options: [{ id: "A", text: "6", isCorrect: true }, { id: "B", text: "4", isCorrect: false }, { id: "C", text: "3", isCorrect: false }, { id: "D", text: "8", isCorrect: false }] },
  { id: "ch8_7_10", category: "Chương 8 - Bài 7", image: "/images/math7.png", timeLimit: 45, question: "Cho G là trọng tâm, $AM=9$. Độ dài $AG$ là:", options: [{ id: "A", text: "6", isCorrect: true }, { id: "B", text: "3", isCorrect: false }, { id: "C", text: "4.5", isCorrect: false }, { id: "D", text: "2.5", isCorrect: false }] },

  // BÀI 8: Tính chất ba đường cao của tam giác
  { id: "ch8_8_1", category: "Chương 8 - Bài 8", image: "/images/math7.png", timeLimit: 30, question: "Giao điểm của ba đường cao trong tam giác gọi là:", options: [{ id: "A", text: "Trực tâm", isCorrect: true }, { id: "B", text: "Trọng tâm", isCorrect: false }, { id: "C", text: "Tâm nội tiếp", isCorrect: false }, { id: "D", text: "Tâm ngoại tiếp", isCorrect: false }] },
  { id: "ch8_8_2", category: "Chương 8 - Bài 8", image: "/images/math7.png", timeLimit: 30, question: "Đường cao của tam giác kẻ từ một đỉnh là đoạn vuông góc kẻ từ đỉnh đó đến:", options: [{ id: "A", text: "Đường thẳng chứa cạnh đối diện", isCorrect: true }, { id: "B", text: "Trung điểm cạnh đối", isCorrect: false }, { id: "C", text: "Góc đối", isCorrect: false }, { id: "D", text: "Giao điểm phân giác", isCorrect: false }] },
  { id: "ch8_8_3", category: "Chương 8 - Bài 8", image: "/images/math7.png", timeLimit: 45, question: "Trong tam giác tù, trực tâm nằm ở đâu?", options: [{ id: "A", text: "Bên ngoài tam giác", isCorrect: true }, { id: "B", text: "Bên trong tam giác", isCorrect: false }, { id: "C", text: "Tại đỉnh nhọn", isCorrect: false }, { id: "D", text: "Tại đỉnh tù", isCorrect: false }] },
  { id: "ch8_8_4", category: "Chương 8 - Bài 8", image: "/images/math7.png", timeLimit: 45, question: "Trong t/g vuông, trực tâm trùng với:", options: [{ id: "A", text: "Đỉnh góc vuông", isCorrect: true }, { id: "B", text: "Trung điểm cạnh huyền", isCorrect: false }, { id: "C", text: "Trọng tâm", isCorrect: false }, { id: "D", text: "Đỉnh góc nhọn", isCorrect: false }] },
  { id: "ch8_8_5", category: "Chương 8 - Bài 8", image: "/images/math7.png", timeLimit: 45, question: "Ba đường cao của t/g nhọn giao nhau ở đâu?", options: [{ id: "A", text: "Bên trong tam giác", isCorrect: true }, { id: "B", text: "Bên ngoài", isCorrect: false }, { id: "C", text: "Lên cạnh", isCorrect: false }, { id: "D", text: "Trùng với trọng tâm", isCorrect: false }] },
  { id: "ch8_8_6", category: "Chương 8 - Bài 8", image: "/images/math7.png", timeLimit: 45, question: "Trong t/g cân, đường cao ứng với cạnh đáy cũng có tính chất là?", options: [{ id: "A", text: "Là đường phân giác, trung tuyến, trung trực", isCorrect: true }, { id: "B", text: "Không có tính chất gì", isCorrect: false }, { id: "C", text: "Chỉ là trung trực", isCorrect: false }, { id: "D", text: "Nằm ngoài tam giác", isCorrect: false }] },
  { id: "ch8_8_7", category: "Chương 8 - Bài 8", image: "/images/math7.png", timeLimit: 45, question: "Khẳng định nào đúng: Mọi tam giác đều có ... đường cao", options: [{ id: "A", text: "3", isCorrect: true }, { id: "B", text: "1", isCorrect: false }, { id: "C", text: "2", isCorrect: false }, { id: "D", text: "Vô số", isCorrect: false }] },
  { id: "ch8_8_8", category: "Chương 8 - Bài 8", image: "/images/math7.png", timeLimit: 45, question: "Trực tâm, tâm ngoại tiếp, trọng tâm của 1 tam giác thường luôn:", options: [{ id: "A", text: "Cùng nằm trên đường thẳng Euler", isCorrect: true }, { id: "B", text: "Không bao giờ thẳng hàng", isCorrect: false }, { id: "C", text: "Trùng nhau", isCorrect: false }, { id: "D", text: "Cách đều ba đỉnh", isCorrect: false }] },
  { id: "ch8_8_9", category: "Chương 8 - Bài 8", image: "/images/math7.png", timeLimit: 45, question: "Đường cao lớn nhất luôn kẻ tới cạnh:", options: [{ id: "A", text: "Ngắn nhất của tam giác", isCorrect: true }, { id: "B", text: "Dài nhất", isCorrect: false }, { id: "C", text: "Trung bình", isCorrect: false }, { id: "D", text: "Không xác định", isCorrect: false }] },
  { id: "ch8_8_10", category: "Chương 8 - Bài 8", image: "/images/math7.png", timeLimit: 45, question: "Diện tích tam giác tính theo đường cao h và đáy a là:", options: [{ id: "A", text: "$S = \\frac{1}{2}ah$", isCorrect: true }, { id: "B", text: "$S = a + h$", isCorrect: false }, { id: "C", text: "$S = ah$", isCorrect: false }, { id: "D", text: "$S = \\frac{ah}{3}$", isCorrect: false }] },

  // BÀI 9: Tính chất ba đường phân giác của tam giác
  { id: "ch8_9_1", category: "Chương 8 - Bài 9", image: "/images/math7.png", timeLimit: 30, question: "Giao điểm của ba đường phân giác trong tam giác được gọi là:", options: [{ id: "A", text: "Tâm đường tròn nội tiếp", isCorrect: true }, { id: "B", text: "Trực tâm", isCorrect: false }, { id: "C", text: "Tâm đường tròn ngoại tiếp", isCorrect: false }, { id: "D", text: "Trọng tâm", isCorrect: false }] },
  { id: "ch8_9_2", category: "Chương 8 - Bài 9", image: "/images/math7.png", timeLimit: 45, question: "Điểm cách đều 3 cạnh của tam giác là giao điểm của:", options: [{ id: "A", text: "3 đường phân giác", isCorrect: true }, { id: "B", text: "3 đường cao", isCorrect: false }, { id: "C", text: "3 trung tuyến", isCorrect: false }, { id: "D", text: "3 trung trực", isCorrect: false }] },
  { id: "ch8_9_3", category: "Chương 8 - Bài 9", image: "/images/math7.png", timeLimit: 45, question: "Tính chất của một điểm trên phân giác của góc là:", options: [{ id: "A", text: "Cách đều hai cạnh tạo thành góc đó", isCorrect: true }, { id: "B", text: "Gần cạnh này hơn cạnh kia", isCorrect: false }, { id: "C", text: "Luôn vuông góc", isCorrect: false }, { id: "D", text: "Chia góc thành tỉ lệ vàng", isCorrect: false }] },
  { id: "ch8_9_4", category: "Chương 8 - Bài 9", image: "/images/math7.png", timeLimit: 45, question: "Tâm nội tiếp tam giác luôn nằm ở đâu?", options: [{ id: "A", text: "Luôn nằm bên trong tam giác", isCorrect: true }, { id: "B", text: "Nằm trên cạnh chữ nhật", isCorrect: false }, { id: "C", text: "Bên ngoài 1 góc", isCorrect: false }, { id: "D", text: "Trung điểm cạnh", isCorrect: false }] },
  { id: "ch8_9_5", category: "Chương 8 - Bài 9", image: "/images/math7.png", timeLimit: 45, question: "Đường tròn nội tiếp tam giác có bao nhiêu tiếp tuyến chung với các cạnh?", options: [{ id: "A", text: "Tiếp xúc với cả 3 cạnh", isCorrect: true }, { id: "B", text: "Cắt tại 6 điểm", isCorrect: false }, { id: "C", text: "Đi qua 3 đỉnh", isCorrect: false }, { id: "D", text: "Không có", isCorrect: false }] },
  { id: "ch8_9_6", category: "Chương 8 - Bài 9", image: "/images/math7.png", timeLimit: 45, question: "Nếu I là tâm nội tiếp t/g ABC vuông cân tại A thì góc BIC = ?", options: [{ id: "A", text: "$135^\\circ$", isCorrect: true }, { id: "B", text: "$45^\\circ$", isCorrect: false }, { id: "C", text: "$90^\\circ$", isCorrect: false }, { id: "D", text: "$120^\\circ$", isCorrect: false }] },
  { id: "ch8_9_7", category: "Chương 8 - Bài 9", image: "/images/math7.png", timeLimit: 45, question: "Tia phân giác chia góc thành:", options: [{ id: "A", text: "Hai góc bằng nhau bằng một nửa góc ban đầu", isCorrect: true }, { id: "B", text: "Ba phần", isCorrect: false }, { id: "C", text: "Hai tia vuông góc", isCorrect: false }, { id: "D", text: "Tia đối", isCorrect: false }] },
  { id: "ch8_9_8", category: "Chương 8 - Bài 9", image: "/images/math7.png", timeLimit: 45, question: "Tam giác đều thì:", options: [{ id: "A", text: "Trọng tâm trùng với Tâm nội tiếp", isCorrect: true }, { id: "B", text: "Tâm nội tiếp nằm ngoài", isCorrect: false }, { id: "C", text: "Trung điểm khác xa", isCorrect: false }, { id: "D", text: "Trực tâm nằm ngoài", isCorrect: false }] },
  { id: "ch8_9_9", category: "Chương 8 - Bài 9", image: "/images/math7.png", timeLimit: 45, question: "Đường thẳng chia $\\widehat{A}$ của t/g ABC thành 2 phần bằng nhau gọi là:", options: [{ id: "A", text: "Đường phân giác trong của góc A", isCorrect: true }, { id: "B", text: "Đường xiên", isCorrect: false }, { id: "C", text: "Phân giác ngoài", isCorrect: false }, { id: "D", text: "Trung trực", isCorrect: false }] },
  { id: "ch8_9_10", category: "Chương 8 - Bài 9", image: "/images/math7.png", timeLimit: 45, question: "Với I là tâm nội tiếp, kẻ IH vuông góc BC. Đoạn IH là:", options: [{ id: "A", text: "Bán kính đường tròn nội tiếp", isCorrect: true }, { id: "B", text: "Đường kính đường tròn bàng tiếp", isCorrect: false }, { id: "C", text: "Cạnh của tam giác", isCorrect: false }, { id: "D", text: "Bán kính đường tròn ngoại tiếp", isCorrect: false }] }
];
