export const questions_ch9 = [
  // Bài 1: Mô tả xác suất bằng tỉ số (10 câu)
  { id: "ch9_1_1", category: "Chương 9 - Bài 1", timeLimit: 30, question: "Xác suất của biến cố A, kí hiệu là $P(A)$, luôn thoả mãn điều kiện nào?", options: [{ id: "A", text: "$P(A) < 0$", isCorrect: false }, { id: "B", text: "$P(A) > 1$", isCorrect: false }, { id: "C", text: "$0 \\le P(A) \\le 1$", isCorrect: true }, { id: "D", text: "$P(A) = 2$", isCorrect: false }] },
  { id: "ch9_1_2", category: "Chương 9 - Bài 1", timeLimit: 30, question: "Kí hiệu xác suất của biến cố ngẫu nhiên lấy giá trị tỉ số $P(A)$ được đo bằng:", options: [{ id: "A", text: "Số thực trên 1", isCorrect: false }, { id: "B", text: "Số lượng thuận lợi chia tổng số lượng đồng khả năng", isCorrect: true }, { id: "C", text: "Hiệu đồng khả năng", isCorrect: false }, { id: "D", text: "Tổng trung bình cộng", isCorrect: false }] },
  { id: "ch9_1_3", category: "Chương 9 - Bài 1", timeLimit: 30, question: "Nếu tung đồng xu 1 lần, xác suất ra mặt ngửa là:", options: [{ id: "A", text: "$\\frac{1}{4}$", isCorrect: false }, { id: "B", text: "$1$", isCorrect: false }, { id: "C", text: "$\\frac{1}{3}$", isCorrect: false }, { id: "D", text: "$\\frac{1}{2}$", isCorrect: true }] },
  { id: "ch9_1_4", category: "Chương 9 - Bài 1", timeLimit: 30, question: "Trong bình có 4 bi đỏ, 6 bi xanh. Xác suất rút được bi đỏ là:", options: [{ id: "A", text: "$0.6$", isCorrect: false }, { id: "B", text: "$0.4$", isCorrect: true }, { id: "C", text: "$0.5$", isCorrect: false }, { id: "D", text: "$4$", isCorrect: false }] },
  { id: "ch9_1_5", category: "Chương 9 - Bài 1", timeLimit: 30, question: "Gieo 1 xúc xắc 6 mặt tròn đều. Xác suất ra mặt 7 là:", options: [{ id: "A", text: "1", isCorrect: false }, { id: "B", text: "0", isCorrect: true }, { id: "C", text: "0.5", isCorrect: false }, { id: "D", text: "6/7", isCorrect: false }] },
  { id: "ch9_1_6", category: "Chương 9 - Bài 1", timeLimit: 30, question: "Xác suất của biến cố chắc chắn luôn có tỉ số là:", options: [{ id: "A", text: "0", isCorrect: false }, { id: "B", text: "0.5", isCorrect: false }, { id: "C", text: "1", isCorrect: true }, { id: "D", text: "100", isCorrect: false }] },
  { id: "ch9_1_7", category: "Chương 9 - Bài 1", timeLimit: 30, question: "Từ tập $\\{1, 2, 3, 4, 5\\}$. Rút ngẫu nhiên một số. Xác suất ra số chẵn là:", options: [{ id: "A", text: "$40\\%$", isCorrect: true }, { id: "B", text: "$60\\%$", isCorrect: false }, { id: "C", text: "$50\\%$", isCorrect: false }, { id: "D", text: "$20\\%$", isCorrect: false }] },
  { id: "ch9_1_8", category: "Chương 9 - Bài 1", timeLimit: 30, question: "Tỉ số thuận lợi là khái niệm xuất phát từ:", options: [{ id: "A", text: "Đếm số lần khả năng tạo thành biến cố cần tính", isCorrect: true }, { id: "B", text: "Sai số ngẫu nhiên", isCorrect: false }, { id: "C", text: "Ngoại lực", isCorrect: false }, { id: "D", text: "Tích chéo", isCorrect: false }] },
  { id: "ch9_1_9", category: "Chương 9 - Bài 1", timeLimit: 30, question: "Xác suất biến cố không thể xảy ra luôn mang tỉ số là:", options: [{ id: "A", text: "Vô tận", isCorrect: false }, { id: "B", text: "Không xác định", isCorrect: false }, { id: "C", text: "$1$", isCorrect: false }, { id: "D", text: "$0$", isCorrect: true }] },
  { id: "ch9_1_10", category: "Chương 9 - Bài 1", timeLimit: 30, question: "Một bộ bài 52 lá. Rút ngẫu nhiên 1 lá. Xác suất rút được lá Át là:", options: [{ id: "A", text: "$\\frac{1}{52}$", isCorrect: false }, { id: "B", text: "$\\frac{1}{13}$", isCorrect: true }, { id: "C", text: "$\\frac{4}{13}$", isCorrect: false }, { id: "D", text: "$\\frac{1}{4}$", isCorrect: false }] },

  // Bài 2: Xác suất lí thuyết và xác suất thực nghiệm (10 câu)
  { id: "ch9_2_1", category: "Chương 9 - Bài 2", timeLimit: 30, question: "Xác suất thực nghiệm là gì?", options: [{ id: "A", text: "Kết quả đo lường sau khi thực hiện nhiều lần phép thử nghiệm", isCorrect: true }, { id: "B", text: "Chỉ là phỏng đoán", isCorrect: false }, { id: "C", text: "Tương đương giá trị biến", isCorrect: false }, { id: "D", text: "Không áp dụng cho thống kê", isCorrect: false }] },
  { id: "ch9_2_2", category: "Chương 9 - Bài 2", timeLimit: 30, question: "Khẳng định đúng về mối liên hệ xác suất lí thuyết và thực nghiệm:", options: [{ id: "A", text: "Thực nghiệm luôn bằng lí thuyết", isCorrect: false }, { id: "B", text: "Khi thử nghiệm số lần đủ lớn, xác suất thực nghiệm xấp xỉ xác suất lí thuyết", isCorrect: true }, { id: "C", text: "Không có sự liên kết", isCorrect: false }, { id: "D", text: "Có sai số $100\\%$", isCorrect: false }] },
  { id: "ch9_2_3", category: "Chương 9 - Bài 2", timeLimit: 30, question: "Gieo đồng xu $100$ lần thấy $45$ lần sấp. Xác suất thực nghiệm ra sấp là:", options: [{ id: "A", text: "$55\\%$", isCorrect: false }, { id: "B", text: "$50\\%$", isCorrect: false }, { id: "C", text: "$45\\%$", isCorrect: true }, { id: "D", text: "$100\\%$", isCorrect: false }] },
  { id: "ch9_2_4", category: "Chương 9 - Bài 2", timeLimit: 30, question: "Xác suất lí thuyết tung đồng xu ra sấp là:", options: [{ id: "A", text: "$50\\%$", isCorrect: true }, { id: "B", text: "$45\\%$", isCorrect: false }, { id: "C", text: "$55\\%$", isCorrect: false }, { id: "D", text: "$100\\%$", isCorrect: false }] },
  { id: "ch9_2_5", category: "Chương 9 - Bài 2", timeLimit: 30, question: "Gieo xúc xắc 120 lần, mặt 6 chấm ra 22 lần. Xác suất thực nghiệm ra 6 chấm là:", options: [{ id: "A", text: "$\\frac{1}{6}$", isCorrect: false }, { id: "B", text: "$\\frac{22}{120}$", isCorrect: true }, { id: "C", text: "$0.5$", isCorrect: false }, { id: "D", text: "$\\frac{1}{5}$", isCorrect: false }] },
  { id: "ch9_2_6", category: "Chương 9 - Bài 2", timeLimit: 30, question: "Với số lần thử $n \\rightarrow \\infty$, độ lệch giữa 2 loại xác suất sẽ:", options: [{ id: "A", text: "Chẳng thay đổi", isCorrect: false }, { id: "B", text: "Nhanh chóng thành $1$", isCorrect: false }, { id: "C", text: "Tiến dần về $0$", isCorrect: true }, { id: "D", text: "Sẽ chênh lệch càng lớn", isCorrect: false }] },
  { id: "ch9_2_7", category: "Chương 9 - Bài 2", timeLimit: 30, question: "Nhà trường kiểm tra 100 bóng đèn thì 2 hỏng. Vậy theo thực nghiệm, mua ngẫu nhiên đèn có xác suất bị hỏng là:", options: [{ id: "A", text: "$10\\%$", isCorrect: false }, { id: "B", text: "$98\\%$", isCorrect: false }, { id: "C", text: "$2\\%$", isCorrect: true }, { id: "D", text: "$5\\%$", isCorrect: false }] },
  { id: "ch9_2_8", category: "Chương 9 - Bài 2", timeLimit: 30, question: "Mục đích lớn nhất khi dùng xác suất thực nghiệm là:", options: [{ id: "A", text: "Để giải bài tập toán phức tạp", isCorrect: false }, { id: "B", text: "Để có bài thi dài", isCorrect: false }, { id: "C", text: "Tính nhẩm cho trẻ em", isCorrect: false }, { id: "D", text: "Dự đoán, ước lượng đánh giá các hiện tượng đo thực tế", isCorrect: true }] },
  { id: "ch9_2_9", category: "Chương 9 - Bài 2", timeLimit: 30, question: "Xác suất thực nghiệm và tần suất tương đối trong thống kê là:", options: [{ id: "A", text: "Hai khái niệm tương đồng", isCorrect: true }, { id: "B", text: "Trái ngược nhau", isCorrect: false }, { id: "C", text: "Bù trừ nhau", isCorrect: false }, { id: "D", text: "Góc vuông vuông", isCorrect: false }] },
  { id: "ch9_2_10", category: "Chương 9 - Bài 2", timeLimit: 30, question: "Có 5 bạn thi đấu cờ. A thắng B 7/10 trận. Kết luận A mạnh hơn B là dựa trên:", options: [{ id: "A", text: "Giả thuyết cảm tính", isCorrect: false }, { id: "B", text: "Độ đo tâm đồ", isCorrect: false }, { id: "C", text: "Lực lượng", isCorrect: false }, { id: "D", text: "Phân tích xác suất thực nghiệm", isCorrect: true }] }
];
