export const questions_ch8 = [
  // Bài 1: Hai tam giác đồng dạng (10 câu)
  { id: "ch8_1_1", category: "Chương 8 - Bài 1", timeLimit: 30, image: "/images/similar_triangles.png", question: "Hai tam giác gọi là đồng dạng nếu:", options: [{ id: "A", text: "Ba góc tương ứng bằng nhau và ba cạnh bên bằng nhau", isCorrect: false }, { id: "B", text: "Ba góc tương ứng tỉ lệ thuận và ba cạnh tương ứng bằng nhau", isCorrect: false }, { id: "C", text: "Chỉ ba cặp góc tương ứng bằng nhau", isCorrect: false }, { id: "D", text: "Ba góc tương ứng bằng nhau và ba cạnh tương ứng tỉ lệ", isCorrect: true }] },
  { id: "ch8_1_2", category: "Chương 8 - Bài 1", timeLimit: 30, image: "/images/similar_triangles.png", question: "Kí hiệu của sự đồng dạng là:", options: [{ id: "A", text: "$\\sim$", isCorrect: true }, { id: "B", text: "$=$", isCorrect: false }, { id: "C", text: "$\\cong$", isCorrect: false }, { id: "D", text: "$\\parallel$", isCorrect: false }] },
  { id: "ch8_1_3", category: "Chương 8 - Bài 1", timeLimit: 30, image: "/images/similar_triangles.png", question: "Tỉ số đồng dạng $k$ là:", options: [{ id: "A", text: "Tỉ số giữa góc tương ứng", isCorrect: false }, { id: "B", text: "Tỉ số giữa hai cạnh tương ứng của hai tam giác đồng dạng", isCorrect: true }, { id: "C", text: "Tích hai cạnh tạo nên chúng", isCorrect: false }, { id: "D", text: "Tổng hai cạnh huyền", isCorrect: false }] },
  { id: "ch8_1_4", category: "Chương 8 - Bài 1", timeLimit: 30, image: "/images/similar_triangles.png", question: "Cho $\\Delta ABC \\sim \\Delta MNP$ với $k = \\frac{1}{2}$. Chu vi $\\Delta ABC$ và $\\Delta MNP$ tỉ lệ:", options: [{ id: "A", text: "Tỉ lệ bình phương là $\\frac{1}{4}$", isCorrect: false }, { id: "B", text: "Tỉ lệ là 2", isCorrect: false }, { id: "C", text: "Là $1$", isCorrect: false }, { id: "D", text: "Tỉ lệ là $\\frac{1}{2}$", isCorrect: true }] },
  { id: "ch8_1_5", category: "Chương 8 - Bài 1", timeLimit: 30, image: "/images/similar_triangles.png", question: "Khẳng định nào đúng về tam giác đồng dạng?", options: [{ id: "A", text: "Hai tam giác bằng nhau thì luôn đồng dạng với tỉ số $k = 1$", isCorrect: true }, { id: "B", text: "Mọi tam giác đồng dạng đều bằng nhau", isCorrect: false }, { id: "C", text: "Tam giác đều không thể đồng dạng", isCorrect: false }, { id: "D", text: "Cần xét góc nhọn thì mới đồng dạng", isCorrect: false }] },
  { id: "ch8_1_6", category: "Chương 8 - Bài 1", timeLimit: 30, image: "/images/similar_triangles.png", question: "Hai tam giác đều:", options: [{ id: "A", text: "Luôn đồng dạng với nhau", isCorrect: true }, { id: "B", text: "Đồng dạng khi cùng chu vi", isCorrect: false }, { id: "C", text: "Chỉ đồng dạng khi bằng nhau", isCorrect: false }, { id: "D", text: "Chưa chắc đồng dạng", isCorrect: false }] },
  { id: "ch8_1_7", category: "Chương 8 - Bài 1", timeLimit: 30, image: "/images/similar_triangles.png", question: "Hai tam giác $\\Delta ABC \\sim \\Delta DEF$ tỉ số $k$. Diện tích của hai tam giác này tỉ lệ bằng:", options: [{ id: "A", text: "$k^2$", isCorrect: true }, { id: "B", text: "$k^3$", isCorrect: false }, { id: "C", text: "$k$", isCorrect: false }, { id: "D", text: "$2k$", isCorrect: false }] },
  { id: "ch8_1_8", category: "Chương 8 - Bài 1", timeLimit: 30, image: "/images/similar_triangles.png", question: "Đường thẳng chia một tam giác thành tam giác nhỏ đồng dạng tam giác lớn là:", options: [{ id: "A", text: "Đường thẳng qua trọng tâm", isCorrect: false }, { id: "B", text: "Đường trung tuyến của tam giác", isCorrect: false }, { id: "C", text: "Đường thẳng song song với một cạnh", isCorrect: true }, { id: "D", text: "Không có đường thẳng nào", isCorrect: false }] },
  { id: "ch8_1_9", category: "Chương 8 - Bài 1", timeLimit: 30, image: "/images/similar_triangles.png", question: "Cho $\\Delta ABC \\sim \\Delta DEF$. Nếu $\\hat{A} = 40^\\circ$ thì góc $\\hat{D}$ là:", options: [{ id: "A", text: "$50^\\circ$", isCorrect: false }, { id: "B", text: "$40^\\circ$", isCorrect: true }, { id: "C", text: "$140^\\circ$", isCorrect: false }, { id: "D", text: "$60^\\circ$", isCorrect: false }] },
  { id: "ch8_1_10", category: "Chương 8 - Bài 1", timeLimit: 30, image: "/images/similar_triangles.png", question: "Tỉ số đường cao tương ứng của hai tam giác đồng dạng:", options: [{ id: "A", text: "Bằng bình phương tỉ số đồng dạng $k$", isCorrect: false }, { id: "B", text: "Không xác định", isCorrect: false }, { id: "C", text: "Gấp 2 lần tỉ số đồng dạng $k$", isCorrect: false }, { id: "D", text: "Bằng tỉ số đồng dạng $k$", isCorrect: true }] },

  // Bài 2: Các trường hợp đồng dạng của hai tam giác (10 câu)
  { id: "ch8_2_1", category: "Chương 8 - Bài 2", timeLimit: 30, image: "/images/similar_triangles.png", question: "Trường hợp đồng dạng thứ nhất (c-c-c):", options: [{ id: "A", text: "Ba cặp cạnh bằng nhau", isCorrect: false }, { id: "B", text: "Hai cạnh tỉ lệ, một góc xen giữa", isCorrect: false }, { id: "C", text: "Ba cạnh của tam giác này tỉ lệ với ba cạnh tam giác kia", isCorrect: true }, { id: "D", text: "Ba cặp góc tỉ lệ với nhau", isCorrect: false }] },
  { id: "ch8_2_2", category: "Chương 8 - Bài 2", timeLimit: 30, image: "/images/similar_triangles.png", question: "Trường hợp đồng dạng thứ hai (c-g-c):", options: [{ id: "A", text: "Hai cặp góc bằng nhau, một cặp cạnh kề tỉ lệ", isCorrect: false }, { id: "B", text: "Hai góc kề một đáy cạnh", isCorrect: false }, { id: "C", text: "Hai cạnh của tam giác này tỉ lệ với hai cạnh tam giác kia kẹp góc bằng", isCorrect: false }, { id: "D", text: "Hai cạnh tam giác tỉ lệ với hai cạnh kia và góc xen giữa hai cạnh đó bằng nhau", isCorrect: true }] },
  { id: "ch8_2_3", category: "Chương 8 - Bài 2", timeLimit: 30, image: "/images/similar_triangles.png", question: "Trường hợp đồng dạng thứ ba (g-g) chỉ cần xét:", options: [{ id: "A", text: "2 góc của tam giác này bằng 2 góc của tam giác kia", isCorrect: true }, { id: "B", text: "2 cạnh bàng nhau 1 góc", isCorrect: false }, { id: "C", text: "3 góc đối nhau", isCorrect: false }, { id: "D", text: "1 góc bằng 2 góc tỉ lệ", isCorrect: false }] },
  { id: "ch8_2_4", category: "Chương 8 - Bài 2", timeLimit: 30, image: "/images/similar_triangles.png", question: "Để chứng minh tam giác dạng c-g-c, góc đó phải là góc:", options: [{ id: "A", text: "Góc tù", isCorrect: false }, { id: "B", text: "Góc bất kì trong hình", isCorrect: false }, { id: "C", text: "Góc tạo bởi hai cạnh được dùng để lập tỉ lệ", isCorrect: true }, { id: "D", text: "Góc vuông", isCorrect: false }] },
  { id: "ch8_2_5", category: "Chương 8 - Bài 2", timeLimit: 30, image: "/images/similar_triangles.png", question: "Tam giác vuông cân đồng dạng với nhau khi:", options: [{ id: "A", text: "Chúng cùng chu vi", isCorrect: false }, { id: "B", text: "Luôn luôn đồng dạng", isCorrect: true }, { id: "C", text: "Diện tích cùng là 1 đơn vị", isCorrect: false }, { id: "D", text: "Cạnh bằng nhau", isCorrect: false }] },
  { id: "ch8_2_6", category: "Chương 8 - Bài 2", timeLimit: 30, image: "/images/similar_triangles.png", question: "Cho $\\Delta ABC$ có $AB=4, AC=6, BC=5$. $\\Delta DEF$ có $DE=8, DF=12$. Nếu $EF = 10$ thì:", options: [{ id: "A", text: "Hai tam giác đồng dạng với $k=1/2$", isCorrect: true }, { id: "B", text: "Hai tam giác đồng dạng tỉ số $k=2$", isCorrect: false }, { id: "C", text: "Không thể nhận xét", isCorrect: false }, { id: "D", text: "Đồng dạng nhưng sai cạnh", isCorrect: false }] },
  { id: "ch8_2_7", category: "Chương 8 - Bài 2", timeLimit: 30, image: "/images/similar_triangles.png", question: "Nếu $\\Delta ABC$ và $\\Delta MNP$ có $\\hat{B} = \\hat{N}$ và $\\frac{AB}{MN} = \\frac{BC}{NP}$ thì:", options: [{ id: "A", text: "Thiếu dữ kiện chứng minh đồng dạng", isCorrect: false }, { id: "B", text: "Cần kiểm tra cạnh còn lại", isCorrect: false }, { id: "C", text: "Đồng dạng vì góc B không kẹp giữa 2 cạnh", isCorrect: false }, { id: "D", text: "Đồng dạng vì thỏa mãn c-g-c do 2 góc đều xen giữa", isCorrect: true }] },
  { id: "ch8_2_8", category: "Chương 8 - Bài 2", timeLimit: 30, image: "/images/similar_triangles.png", question: "Nếu tam giác có hai góc lần lượt là $40^\\circ, 60^\\circ$ và tam giác kia cũng $40^\\circ, 60^\\circ$ thì:", options: [{ id: "A", text: "Hai tam giác không có tính chất đồng dạng", isCorrect: false }, { id: "B", text: "Vuông góc", isCorrect: false }, { id: "C", text: "Hai tam giác bằng nhau", isCorrect: false }, { id: "D", text: "Hai tam giác đồng dạng theo trường hợp g-g", isCorrect: true }] },
  { id: "ch8_2_9", category: "Chương 8 - Bài 2", timeLimit: 30, image: "/images/similar_triangles.png", question: "Quy tắc viết tên hai tam giác đồng dạng:", options: [{ id: "A", text: "Phải viết các đỉnh tương ứng theo đúng thứ tự", isCorrect: true }, { id: "B", text: "Viết không cần quan tâm góc", isCorrect: false }, { id: "C", text: "Nào dài hơn viết trước", isCorrect: false }, { id: "D", text: "Ngẫu nhiên", isCorrect: false }] },
  { id: "ch8_2_10", category: "Chương 8 - Bài 2", timeLimit: 30, image: "/images/similar_triangles.png", question: "Khi chỉ biết hai cặp cạnh của 2 tam giác tỉ lệ với nhau, ta có kết luận chúng đồng dạng chưa?", options: [{ id: "A", text: "Có", isCorrect: false }, { id: "B", text: "Đồng dạng vuông", isCorrect: false }, { id: "C", text: "Chưa", isCorrect: true }, { id: "D", text: "Sai toàn tập", isCorrect: false }] },

  // Bài 3: Các trường hợp đồng dạng của hai tam giác vuông (10 câu)
  { id: "ch8_3_1", category: "Chương 8 - Bài 3", timeLimit: 30, image: "/images/similar_triangles.png", question: "Hai tam giác vuông đồng dạng khi:", options: [{ id: "A", text: "Chỉ cần 1 góc vuông", isCorrect: false }, { id: "B", text: "Một góc nhọn của tam giác này bằng một góc nhọn của tam giác kia", isCorrect: true }, { id: "C", text: "Hai cạnh góc vuông bằng nhau", isCorrect: false }, { id: "D", text: "Cạnh huyền chia đôi", isCorrect: false }] },
  { id: "ch8_3_2", category: "Chương 8 - Bài 3", timeLimit: 30, image: "/images/similar_triangles.png", question: "Trong t/g vuông, nếu 2 cạnh góc vuông của t/g này tỉ lệ với 2 cạnh góc vuông của t/g kia thì:", options: [{ id: "A", text: "Tỉ số góc $k$ bị lệch", isCorrect: false }, { id: "B", text: "Chúng đồng dạng", isCorrect: true }, { id: "C", text: "Chúng bằng nhau", isCorrect: false }, { id: "D", text: "Vô lí", isCorrect: false }] },
  { id: "ch8_3_3", category: "Chương 8 - Bài 3", timeLimit: 30, image: "/images/similar_triangles.png", question: "Trường hợp cạnh huyền - cạnh góc vuông:", options: [{ id: "A", text: "Cạnh huyền và một cạnh góc vuông của t/g này tỉ lệ với t/g kia thì chúng đồng dạng", isCorrect: true }, { id: "B", text: "Hàm sai tỉ số $k$", isCorrect: false }, { id: "C", text: "Cạnh kề bên hai cạnh", isCorrect: false }, { id: "D", text: "Luôn chỉ bằng 1", isCorrect: false }] },
  { id: "ch8_3_4", category: "Chương 8 - Bài 3", timeLimit: 30, image: "/images/similar_triangles.png", question: "Đường cao ứng với cạnh huyền chia tam giác vuông thành:", options: [{ id: "A", text: "Hai tam giác bằng nhau", isCorrect: false }, { id: "B", text: "Tam giác đều", isCorrect: false }, { id: "C", text: "Một tam giác đều một nhọn vuông", isCorrect: false }, { id: "D", text: "Hai tam giác đồng dạng với nhau và đồng dạng với tam giác đã cho", isCorrect: true }] },
  { id: "ch8_3_5", category: "Chương 8 - Bài 3", timeLimit: 30, image: "/images/similar_triangles.png", question: "Hệ thức về đường cao trong tam giác vuông $AH^2 = ?$ khi có $H$ là chân đường cao?", options: [{ id: "A", text: "$AH^2 = HB \\cdot HC$", isCorrect: true }, { id: "B", text: "$AH^2 = AB \\cdot AC$", isCorrect: false }, { id: "C", text: "$AH^2 = BH \\cdot BC$", isCorrect: false }, { id: "D", text: "$AH^2 = HC \\cdot CB$", isCorrect: false }] },
  { id: "ch8_3_6", category: "Chương 8 - Bài 3", timeLimit: 30, image: "/images/similar_triangles.png", question: "Để đo cây bóng cao mà không leo lên, ứng dụng đồng dạng gì tốt nhất?", options: [{ id: "A", text: "Bằng góc mặt trời sinh chiều dài bóng tạo tam giác vuông đồng dạng", isCorrect: true }, { id: "B", text: "Pythagore tam giác", isCorrect: false }, { id: "C", text: "Lực kế góc tam", isCorrect: false }, { id: "D", text: "Không áp dụng được", isCorrect: false }] },
  { id: "ch8_3_7", category: "Chương 8 - Bài 3", timeLimit: 30, image: "/images/similar_triangles.png", question: "Nếu $\\Delta ABC$ vuông ở $A$, $AB=3, AC=4$. $\\Delta MNP$ vuông ở $M$, có $MN=6$. Để 2 tam giác đồng dạng cạnh $NP$ phải:", options: [{ id: "A", text: "$NP = 5$", isCorrect: false }, { id: "B", text: "$NP = 7$", isCorrect: false }, { id: "C", text: "$NP = 10$", isCorrect: true }, { id: "D", text: "$NP = 14$", isCorrect: false }] },
  { id: "ch8_3_8", category: "Chương 8 - Bài 3", timeLimit: 30, image: "/images/similar_triangles.png", question: "Hai tam giác vuông đồng dạng thì có cần chứng minh cả góc vuông không?", options: [{ id: "A", text: "Có", isCorrect: false }, { id: "B", text: "Không, vì nó có sẵn góc $90^\\circ$ bằng nhau", isCorrect: true }, { id: "C", text: "Bắt buộc 3 góc nhọn", isCorrect: false }, { id: "D", text: "Chỉ đồng dạng theo tam cạnh", isCorrect: false }] },
  { id: "ch8_3_9", category: "Chương 8 - Bài 3", timeLimit: 30, image: "/images/similar_triangles.png", question: "Từ $AH^2 = HB \\cdot HC$, nếu $HB=4, HC=9$, $AH$ có chiều dài là:", options: [{ id: "A", text: "$5$", isCorrect: false }, { id: "B", text: "$13$", isCorrect: false }, { id: "C", text: "$36$", isCorrect: false }, { id: "D", text: "$6$", isCorrect: true }] },
  { id: "ch8_3_10", category: "Chương 8 - Bài 3", timeLimit: 30, image: "/images/similar_triangles.png", question: "Một góc nhọn $30^\\circ$ ở tam giác $ABC$ (vuông $A$) và tam giác $MNP$ (vuông $N$) có 1 góc $30^\\circ$. Chúng đồng dạng theo:", options: [{ id: "A", text: "c-c-c", isCorrect: false }, { id: "B", text: "g-g", isCorrect: true }, { id: "C", text: "c-g-c", isCorrect: false }, { id: "D", text: "ch-cgv", isCorrect: false }] },

  // Bài 4: Hai hình đồng dạng (10 câu)
  { id: "ch8_4_1", category: "Chương 8 - Bài 4", timeLimit: 30, image: "/images/similar_triangles.png", question: "Hai hình $H$ và $H'$ được gọi là đồng dạng nếu:", options: [{ id: "A", text: "Tồn tại một phép dời hình và phép vị tự để biến hình này thành hình kia", isCorrect: true }, { id: "B", text: "Chỉ nhìn chéo nhau", isCorrect: false }, { id: "C", text: "Hai hình cùng tô một màu", isCorrect: false }, { id: "D", text: "Không có định nghĩa này", isCorrect: false }] },
  { id: "ch8_4_2", category: "Chương 8 - Bài 4", timeLimit: 30, image: "/images/similar_triangles.png", question: "Phép vị tự tỉ số $k$ biến mọi khoảng cách giữa biến mọi đại lượng tuyến tính trên hình như:", options: [{ id: "A", text: "Gấp $1/k$ lần", isCorrect: false }, { id: "B", text: "Bằng đúng $1$", isCorrect: false }, { id: "C", text: "Bình Phương khoảng cách điểm dời", isCorrect: false }, { id: "D", text: "Gấp $k$ lần", isCorrect: true }] },
  { id: "ch8_4_3", category: "Chương 8 - Bài 4", timeLimit: 30, image: "/images/similar_triangles.png", question: "Hai đường tròn luôn có:", options: [{ id: "A", text: "Khác tỉ số và là hai dạng không tương đương", isCorrect: false }, { id: "B", text: "Luôn đồng dạng với nhau", isCorrect: true }, { id: "C", text: "Bằng dạng tỉ số không thể tính", isCorrect: false }, { id: "D", text: "Chắc chắn không bằng nhau", isCorrect: false }] },
  { id: "ch8_4_4", category: "Chương 8 - Bài 4", timeLimit: 30, image: "/images/similar_triangles.png", question: "Hai hình chữ nhật bất kì:", options: [{ id: "A", text: "Luôn đồng dạng", isCorrect: false }, { id: "B", text: "Chưa chắc đồng dạng (phải tỉ lệ dài rộng chiều)", isCorrect: true }, { id: "C", text: "Không bao giờ đồng dạng", isCorrect: false }, { id: "D", text: "Vuông góc đồng dạng", isCorrect: false }] },
  { id: "ch8_4_5", category: "Chương 8 - Bài 4", timeLimit: 30, image: "/images/similar_triangles.png", question: "Hai hình vuông bất kì:", options: [{ id: "A", text: "Không bao giờ đồng dạng", isCorrect: false }, { id: "B", text: "Chưa đồng dạng ngay nếu thiếu vị trí", isCorrect: false }, { id: "C", text: "Hai hình vuông sẽ thành chữ nhật", isCorrect: false }, { id: "D", text: "Luôn đồng dạng với nhau", isCorrect: true }] },
  { id: "ch8_4_6", category: "Chương 8 - Bài 4", timeLimit: 30, question: "Khái niệm đồng dạng hình mở rộng cho đối tượng đa giác và đường tròn gọi chung là:", options: [{ id: "A", text: "Cát tuyến cong", isCorrect: false }, { id: "B", text: "Phép tự tạo", isCorrect: false }, { id: "C", text: "Hình đồng dạng", isCorrect: true }, { id: "D", text: "Luỹ thừa", isCorrect: false }] },
  { id: "ch8_4_7", category: "Chương 8 - Bài 4", timeLimit: 30, question: "Nếu đa giác này đồng dạng với đa giác kia có tỉ số $k$, thì diện tích tỉ số là:", options: [{ id: "A", text: "$k^2$", isCorrect: true }, { id: "B", text: "Căn bậc 2 k", isCorrect: false }, { id: "C", text: "Luôn đúng", isCorrect: false }, { id: "D", text: "$2k$", isCorrect: false }] },
  { id: "ch8_4_8", category: "Chương 8 - Bài 4", timeLimit: 30, question: "Một bản vẽ có tỉ lệ xích $1 : 1000$ là một ví dụ thực tế về:", options: [{ id: "A", text: "Định lý Pythagore", isCorrect: false }, { id: "B", text: "Hình đối xứng", isCorrect: false }, { id: "C", text: "Tâm cân xứng", isCorrect: false }, { id: "D", text: "Hình đồng dạng", isCorrect: true }] },
  { id: "ch8_4_9", category: "Chương 8 - Bài 4", timeLimit: 30, question: "Trong bản đồ phẳng, phép đo tỉ lệ là:", options: [{ id: "A", text: "Hệ số góc cgi", isCorrect: false }, { id: "B", text: "Phép đồng dạng", isCorrect: true }, { id: "C", text: "Trực tâm vị trí tuyến", isCorrect: false }, { id: "D", text: "Bình diện 3D", isCorrect: false }] },
  { id: "ch8_4_10", category: "Chương 8 - Bài 4", timeLimit: 30, question: "Hai con người không cùng kích thước khi chiếu lên hình bóng thì có:", options: [{ id: "A", text: "Không thể nhận xét có đồng dạng không chuẩn hóa", isCorrect: true }, { id: "B", text: "Luôn đồng vị", isCorrect: false }, { id: "C", text: "Phản đồng vị góc", isCorrect: false }, { id: "D", text: "Luôn vị tự", isCorrect: false }] }
];
